### ISSUE TITLE
Separate geometric information from physics discretization for embeddedSurfaceElements.

### ISSUE THREAD

**Issue by CusiniM** [GEOS-DEV/GEOS#1045]
As pointed out by @joshua-white and @af1990 in #826, some information relative to the discretization (e.g., the number of jump enrichments) is stored in the subRegion but it should be moved to the proper physics solver instead whereas the embeddedSurfaceSubregion should only contain geometric information.

**Comment by TotoGaz** [comment]
Closing in favor of the major reorganization we're doing right now.
