### ISSUE TITLE
SSLE-QS-BeamBending test

### ISSUE THREAD

**Issue by sytuannguyen** [GEOS-DEV/GEOS#1274]
**Describe the bug**
The stress visualization of the SSLE-QS-BeamBending test is displayed in a deformed shape.
Also, it is more large strain than small strain.

**To Reproduce**
1. Run the test https://github.com/GEOSX/GEOSX/blob/develop/src/coreComponents/physicsSolvers/solidMechanics/integratedTests/SSLE-QS-beamBending.xml
2. Display the results using visit.

**Expected behavior**
The stress visualization should be displayed in undeformed shape by default for allowing data extraction a long a line using query in visit.

**Screenshots**
![image](https://user-images.githubusercontent.com/45685596/104906924-9d077980-5984-11eb-81c7-6cde766b6df1.png)

**Platform (please complete the following information):**
- Machine: Pangea 
- Compiler: gcc 8.3.0
- GEOSX Version: 105253c

**Additional context**

**Comment by herve-gross** [comment]
Closing as this is VisIt specific.
