### ISSUE TITLE
Replace CUDA_ENABLED with ENABLE_CUDA

### ISSUE THREAD

**Issue by corbett5** [GEOS-DEV/GEOS#1359]
Host configs that disable CUDA `set( CUDA_ENABLED OFF )` when they should be using `ENABLE_CUDA`. There are a few other places as well where `CUDA_ENABLED` is used. We should get rid of all of them, will need to change LvArray host-configs.

Thanks to @jkwashbourne for finding this.

**Comment by paveltomin** [comment]
seems fixed
