### ISSUE TITLE
Integratedtests fail with gcc8.3.1 + cuda on Lassen

### ISSUE THREAD

**Issue by CusiniM** [GEOS-DEV/GEOS#1361]
**Describe the bug**
Many integrated tests fail on Lassen with gcc 8.3.1. It seems to be a somewhat random list of tests (e.g., it's not all tests using a specific solver that are failing).                     

Most of them throw the following error:
`1587-148 Incorrect nesting of loop or single constructs.`

A few others, instead, just go out of memory:

`CUDAassert: out of memory /usr/WS1/GEOS/GEOSX/TPLs_2021-03-01/install-lassen-gcc@8.3.1-release/raja/include/RAJA/policy/cuda/MemUtils_CUDA.hpp 210`

**To Reproduce**
1. Build the code on lassen with gcc.
2. Run the integratedTests.

**Expected behavior**
Tests shoud pass.

**Platform (please complete the following information):**
- LLNL/Lassen 
- Compiler:  gcc 8.3.1

**Comment by TotoGaz** [comment]
@CusiniM is this still relavant? I bet we could close it?

**Comment by paveltomin** [comment]
@CusiniM can be closed?
