### ISSUE TITLE
Lassen integrated tests failures

### ISSUE THREAD

**Issue by corbett5** [GEOS-DEV/GEOS#1372]
- [ ] poroElastic_embFractures run failure https://gist.github.com/corbett5/994a89af42ad9b52561d8724238699ff @CusiniM 
- [ ] All of the PhaseField tests run failure https://gist.github.com/corbett5/e3e0d6dbdacd8c43662e335296f0d749 @andrembcosta

Push any changes to `corbett/fix-lassen-tests` and it's associated integrated tests branch `corbett/fix-lassen` where I was able to fix a few failing tests that just didn't request any GPU's even though they were using them.

**Comment by paveltomin** [comment]
@CusiniM can it be closed?
