### ISSUE TITLE
Spack

### ISSUE THREAD

**Issue by corbett5** [GEOS-DEV/GEOS#1398]
Platforms
- [x] LC
- [ ] OSX @corbett5 
- [x] Ubuntu
- [ ] Docker images @TotoGaz 
- [ ] Pangea2/Pangea3 (is this covered by docker?)

Libraries
- [ ] Mathpresso doesn't have a package, do we need it?
- [ ] VTK does have a package but it's huge, someone should strip it down.
- [x] The support for HYPRE+cuda appears to be there in Spack develop, but I haven't tried.

relates to https://github.com/GEOS-DEV/GEOS/issues/1801

**Comment by corbett5** [comment]
@klevzoff do you think it makes sense to add your spack configs to the repo? Even if they're not going to work on every Ubuntu system maybe they should be added as a template of sorts.

**Comment by corbett5** [comment]
https://github.com/GEOSX/GEOSX/pull/1445 adds hypre-cuda support.

**Comment by TotoGaz** [comment]
Closing in favor of https://github.com/GEOS-DEV/GEOS/issues/1801
I've added the extra items to https://github.com/GEOS-DEV/GEOS/issues/1801 so we only have one ticket for this.
