### ISSUE TITLE
Register data on mesh

### ISSUE THREAD

**Issue by sytuannguyen** [GEOS-DEV/GEOS#1405]
Default value is not correctly set for a field with data of type array2d. The values of all its components as well as its magnitude are nil.

`nodes.registerWrapper< array2d< real64, nodes::TOTAL_DISPLACEMENT_PERM > >( "field2d" ).
      setApplyDefaultValue( 12345 ).
      setPlotLevel( PlotLevel::LEVEL_0 ).
      reference().resizeDimension< 1 >( 3 );`

It is verified default value is correctly set for 1d array:

`nodes.registerWrapper< array1d< real64 > >( "field1d" ).
      setApplyDefaultValue( 12345 ).
      setPlotLevel( PlotLevel::LEVEL_0 );`

**Comment by TotoGaz** [comment]
You are setting all the values of your array to `12345` and **then** you call 
```c++
  /**
   * @brief Resize specific dimensions of the array.
   * @tparam INDICES the indices of the dimensions to resize, should be sorted an unique.
   * @tparam DIMS variadic pack containing the dimension types
   * @param newDims the new dimensions. newDims[ 0 ] will be the new size of
   *        dimensions INDICES[ 0 ].
   * @note This does not preserve the values in the Array unless NDIM == 1.
   */
  template< INDEX_TYPE... INDICES, typename ... DIMS >
  LVARRAY_HOST_DEVICE
  void resizeDimension( DIMS const ... newDims )
```
which verbatimly says `This does not preserve the values in the Array unless NDIM == 1` 😉 
Which is kind of logic: you change the sizes, what do you want to do with the new values?
I think you need to do it in two steps there, or maybe change the order of function calls?

**Comment by rrsettgast** [comment]
@TotoGaz The call to `resizeDimension` will not result in an allocation since the first dimension is still 0. There should be a resize called later through the `Wrapper` interface, which should propagate the default values....at least that is what I would have intended to happen.

**Comment by klevzoff** [comment]
@rrsettgast that might've been the case at some point, but now, considering that `registerDataOnMeshRecursive()` (where presumably the above calls are taking place) is called after `generateMesh()`, I don't think there's a later resize (aside from fracture generation). The only single-index resize occurs immediately in `registerWrapper()`. I think this is also the reason we have `setApplyDefaultValue()` in addition to `setDefaultValue()`?

**Comment by sytuannguyen** [comment]
> I think you need to do it in two steps there, or maybe change the order of function calls?

The first option works well! We can set default values to 2d array after resize its dimension as:

`    nodes.registerWrapper< array2d< real64, nodes::TOTAL_DISPLACEMENT_PERM > >( "field2d" ). 
      setPlotLevel( PlotLevel::LEVEL_0 ).
      reference().resizeDimension< 1 >( 3 );
      
    nodes.registerWrapper< array2d< real64, nodes::TOTAL_DISPLACEMENT_PERM > >( "field2d" ).
      setApplyDefaultValue( 12345 );`
