### ISSUE TITLE
ASCII table output

### ISSUE THREAD

**Issue by joshua-white** [GEOS-DEV/GEOS#1417]
**What is the requested feature?**
Write an `AsciiTableOutput` class derived from `OutputBase` that takes an `array2D` and writes it to output, using path checking and sanitation features from `OutputBase`.  This can replace the TriaxialDriver's direct output, and may be useful for writing solver statistics, etc.

Alternative would be use HDF5 output, but for some data a direct-to-text approach will make the user's life easier.

**Comment by paveltomin** [comment]
can it be closed now since https://github.com/GEOS-DEV/GEOS/pull/2984 is merged?
