### ISSUE TITLE
"Near Wellbore Hydraulic Fracture Propagation" Tutorial/Documentation/Help

### ISSUE THREAD

**Issue by serhiikryvenko16** [GEOS-DEV/GEOS#1680]
I am trying to model the near wellbore effects for hydraulic fracture propagation. The best examples of the model I am trying to set-up is discussed in the papers below: 

https://www.osti.gov/servlets/purl/1581887
https://www.osti.gov/servlets/purl/1581891

I was wondering if there is any tutorial or documentation, or potentially similar xml file available to set up the model similar to the one described in aforementioned papers?

Thanks a lot for your support

**Comment by cssherman** [comment]
Hi @serhiikryvenko16 - I did most of that work using the legacy GEOS code, and am planning to convert the workflow to use GEOSX.  I can keep you up-to-date as I make progress on this

**Comment by serhiikryvenko16** [comment]
@cssherman Thanks a lot for your response and interesting work in this area.
I will be looking forward to any updates from you. Let me know if I can be of any help as well.
