### ISSUE TITLE
Time History and Events: unable to collect after the last time step

### ISSUE THREAD

**Issue by francoishamon** [GEOS-DEV/GEOS#1761]
**Describe the bug**
I was asked to output the state of the system at the end of a simulation using hdf5. I did not find a good way, so if anyone knows how to do that, please jump in. Maybe I am just making a stupid mistake somewhere.

My `maxTime` is 56626560 s
Here is what my `Events` block looks like:

```
    <PeriodicEvent
      name="pressureHistoryCollection"
      timeFrequency="56626559"
      targetExactTimestep="0"      
      target="/Tasks/pressureCollection"/>
    <PeriodicEvent
      name="saturationHistoryCollection"
      timeFrequency="56626559"
      targetExactTimestep="0"      
      target="/Tasks/saturationCollection"/>
    
    <PeriodicEvent
      name="pressureHistoryOutput"
      timeFrequency="56626559"
      targetExactTimestep="0"
      target="/Outputs/pressureHistoryOutput"/>
    <PeriodicEvent
      name="saturationHistoryOutput"
      timeFrequency="56626559"
      targetExactTimestep="0"      
      target="/Outputs/saturationHistoryOutput"/>
    
    <PeriodicEvent
      name="solverApplications1"
      maxEventDt="691200"
      beginTime="0"
      endTime="8640000"
      target="/Solvers/reservoirAndWellsSolver"/>
    <PeriodicEvent
      name="solverApplications2"
      maxEventDt="2115000"
      beginTime="8640000"
      target="/Solvers/reservoirAndWellsSolver"/>
```

Above, I put a `timeFrequency` of `"56626559"` for the `TimeHistory` events, which collects the state of the system at the second-to-last time step. If instead I write `timeFrequency="56626560"`, then I don't get any output at all for the end of the simulation (not even the second-to-last time step). 

I also tried playing with the `targetExactTimestep` field, but it did not help.

I also tried moving the output events after the solver applications events, but it did not help.

**To Reproduce**
1. Checkout and compile the TPLs: `temp/hamon/quansHypre` (to have a working linear solver)
2. Checkout the branch `feature/hamon/forGege` (to have a branch compatible with the TPLs)
3. Run the reproducer attached, called `match_with_eclipse_with_time_history.xml`

[reproducer.zip](https://github.com/GEOSX/GEOSX/files/8006966/reproducer.zip)

**Expected behavior**
GEOSX should output the state of the system at the simulation

**Platform (please complete the following information):**
- LLNL/Quartz
- Compiler: gcc-8.1.0 Release
- GEOSX branch `feature/hamon/forGege` (up to date with `develop`, with a working linear solver)

**Additional context**
@jhuang2601 @wrtobin @cssherman If you know what I need to change in the xml or in the code to fix that, please let me know

**Comment by jhuang2601** [comment]
@francoishamon If you just need to save the final result, how about switch the `PeriodicEvent` to `SoloEvent`? And one more thing, in HDF5 output, the time series dose not reflect the true simulation time. For example, the first time step, it is output as 0 in HDF5 file, which corresponds to the time after the first time interval defined in the `solverApplications1`.

**Comment by cssherman** [comment]
Sure, there are a couple of things that I would suggestt:

1) The EventManager loop ends the loop at maxTime, so you would need to grab the output at the end of the previous cycle.  If targetExactTimeStep="0", then you can choose a targetTime slightly before maxTime and it will execute.

https://github.com/GEOSX/GEOSX/blob/1dc46ce69fc126f0cd492be3f9f78661a434bb5e/src/coreComponents/events/EventManager.cpp#L126

2) Try setting logLevel="1" in the Events block to get more information as to what is going on.  The value of forecast indicates the number of cycles until an event expects to execute, with a value of zero meaning that it will execute on the current cycle.

```
Event: 0 (outputs), dt_request=10, forecast=0
Event: 1 (test), dt_request=1e+100, forecast=1
```

3) Using a nested SoloEvent can help clean up the xml file:

```xml
<Events
    maxTime="56626559"
    logLevel="1">

    <PeriodicEvent
      name="solverApplications1"
      maxEventDt="691200"
      beginTime="0"
      endTime="8640000"
      target="/Solvers/reservoirAndWellsSolver"/>
    <PeriodicEvent
      name="solverApplications2"
      maxEventDt="2115000"
      beginTime="8640000"
      target="/Solvers/reservoirAndWellsSolver"/>

    <!-- If this event is set to occur slightly before maxTime and targetExactTimestep="0",
    then it will occur at the end of the last cycle -->
    <SoloEvent
      name="dataCollection"
      targetTime="56626558"
      targetExactTimestep="0">

     <!-- These execute when the parent does -->
      <PeriodicEvent
        name="pressureHistoryCollection"
        target="/Tasks/pressureCollection"/>
      <PeriodicEvent
        name="saturationHistoryCollection"
        target="/Tasks/saturationCollection"/>
      <PeriodicEvent
        name="pressureHistoryOutput"
        target="/Outputs/pressureHistoryOutput"/>
      <PeriodicEvent
        name="saturationHistoryOutput"
        target="/Outputs/saturationHistoryOutput"/>
    </SoloEvent>

</Events>
```

**Comment by TotoGaz** [comment]
https://github.com/GEOSX/GEOSX/blob/1dc46ce69fc126f0cd492be3f9f78661a434bb5e/src/coreComponents/events/EventManager.cpp#L126
Maybe change `<` into `<=`, but I do not know about the implications too much. And relying on tricky floating points comparisons is surely not a good pattern.

What is the `signal` that a computation is over? Who holds it?
If we could get it, then we could set a `WrapUpEvent` meant to trigger at the end of the simulation?

**Comment by paveltomin** [comment]
@cssherman should we follow @TotoGaz suggestion about `<=` ?

**Comment by paveltomin** [comment]
knock knock
