### ISSUE TITLE
remove alias for `string_array` etc.

### ISSUE THREAD

**Issue by rrsettgast** [GEOS-DEV/GEOS#1766]
So what's our policy about `string_array`? Should we use it or `array1d< string >`?

_Originally posted by @TotoGaz in https://github.com/GEOSX/GEOSX/pull/1682#discussion_r801208733_

We typically have stopped using all of these aliases. It provides very little benefit to have them at this point, so I propose they are all removed.

**Comment by cssherman** [comment]
@rrsettgast - this may also be a good opportunity to tackle some oddities with the type names in the schema since I'll likely need to touch that section of the code (varying between ``std___cxx11_basic_string`` <-> ``std_string`` on different systems for example)
