### ISSUE TITLE
Restart file invalid after a group is removed

### ISSUE THREAD

**Issue by klevzoff** [GEOS-DEV/GEOS#1834]
**Describe the bug**
If one or more groups are removed via `deregisterGroup`, the restart data written for some of the remaining sibling groups becomes garbage.

In practice, this can occurs after a call to `removeUnusedNeighbors()` here:
https://github.com/GEOSX/GEOSX/blob/aa0d5aea5a0d38607094b478aed3d6060e8005d6/src/coreComponents/mesh/mpiCommunications/CommunicationTools.cpp#L770

If any ranks' `NeighborData` is actually removed by this call (which can happen, in particular, when using `VTKMeshGenerator` which produces a slightly generous initial neighbor list), the simulation will proceed fine, but attempting to restart from any checkpoint will cause an exception similar to the following to be thrown:
```
{
  "file": "/home/geosx/thirdPartyLibs/build-gcc8-release/conduit/src/conduit/src/libs/conduit/conduit_node.cpp",
  "line": 13181,
  "message": "Node::as_signed_int() const -- DataType empty at path Problem/domain/MeshBodies/mesh1/meshLevels/Level0/nodeManager/neighborData/1/matchedPartitionBoundaryObjects/__sizedFromParent__ does not equal expected DataType int32"
}
```

**To Reproduce**
A minimal reproducer unit test with more detailed explanation is provided in https://github.com/GEOSX/GEOSX/pull/1833

Another way to trigger is to run (from `build-<config>-release/bin` directory):
```
mpirun -n 5 ./geosx -i ../../inputFiles/compositionalMultiphaseWell/staircase_co2_wells_hybrid_3d.xml
# let it finish
mpirun -n 5 ./geosx -i ../../inputFiles/compositionalMultiphaseWell/staircase_co2_wells_hybrid_3d.xml -r staircase_co2_wells_hybrid_3d_restart_000000012
```
(or any other restart produced by first command)

**Expected behavior**
Restart should be written correctly under any modifications of the group tree.

**Additional information**
  * Going forward, the bug will affect many parallel simulations using VTK mesh import. I wasn't able to get to the bottom of it, but it's rather important that we fix it.
  * For now, restart checking has been temporarily disabled for `staircase_co2_wells_hybrid_3d` test here: https://github.com/GEOSX/integratedTests/pull/206. We should re-enable it after the bug is fixed.
  * An alternative workaround is to disable the removal of unused neighbors. This could have a negative impact on parallel performance, since empty messages will likely keep being sent between "fake" neighbors.

**Comment by francoishamon** [comment]
Hello everyone,

I have a large time-consuming field-scale simulation for which this bug found by @klevzoff makes it impossible to use restarts, which is very inconvenient:
```
file: /work206/workrd/SCR/GEOSX/j0261038/GEOS_debug/thirdPartyLibs/build-pangea2-gcc-mpt@8.3.0-release/conduit/src/conduit/src/libs/conduit/conduit_node.cpp
line: 15160
message:
Node::as_signed_int() const -- DataType empty at path Problem/domain/MeshBodies/mesh/meshLevels/Level0/nodeManager/neighborData/687/matchedPartitionBoundaryObjects/__sizedFromParent__ does not equal expected DataType int32
```

I was wondering if someone could suggest me a way to start debugging it to find the root cause of the bug?

Alternatively, @klevzoff you mentioned above that I can just temporarily disable the removal of unused neighbors in my local branch to make things work. Can I just comment out [this line](https://github.com/GEOS-DEV/GEOS/blob/a736739324b230d7bc34ff94ddcd4fefe0aff961/src/coreComponents/mesh/mpiCommunications/CommunicationTools.cpp#L735) locally to make the restart work on my test case?

Thanks!

**Comment by klevzoff** [comment]
Hi @francoishamon, I fixed the bug in https://github.com/GEOS-DEV/GEOS/pull/2608

(and please don't look at git blame for those lines :D)

**Comment by francoishamon** [comment]
Works great! Thanks very much @klevzoff
