### ISSUE TITLE
Strain tensor and principal stresses and strains as output for mechanical simulations

### ISSUE THREAD

**Issue by rafadep** [GEOS-DEV/GEOS#1871]
**What is the requested feature?**
The output of the strain tensor and the principal stresses and strains for mechanical simulations.

**Describe the solution you'd like**
The stress tensor is already given. It would be useful to other mechanical informations.

**Describe alternatives you've considered**
Strain tensor can be obtained directly from the stress tensor and the stiffness. It could be done during post-treatment but would be better to have these informations as output variables.

**Comment by rrsettgast** [comment]
Hello @rafadep. If you have the strain tensor, you can calculate these the quantities as part of the post-processing. We do this in Visit all the time, I would imagine that paraview has a mechanism to do such a thing?

**Comment by rrsettgast** [comment]
@herve-gross Can you contact @rafadep and see if this can be closed?
