### ISSUE TITLE
Workaround when git-lfs is not fetching the large files in thirdPartyLibs

### ISSUE THREAD

**Issue by drmichaelt7777** [GEOS-DEV/GEOS#1957]
**What needs to be documented?**

A clear description of a workaround for when git-lfs is not working for any number of different reasons. 

**What sort of documentation would help?**
Just highlight the steps in the installation and build stages the user should manually take to build GEOSX/thirdPartyLibs when git-lfs is not fetching the large files in thirdPartyLibs

**What are the deficiencies of the existing documentation?**
Sure, it's just a walkthrough of the manual steps.

**Additional notes or context**

**Comment by joshua-white** [comment]
Could you describe why your git-lfs is not working?  What was your ultimate workaround?

**Comment by TotoGaz** [comment]
Hello, as we're moving soon to a different solution (`spack`), I think we'll be able to refer to its offline solutions.

**Comment by drmichaeltcvx** [comment]
As a note: organizational firewalls may block access to github's git-lfs sites breaking this capability.
