### ISSUE TITLE
Rollback azure pipeline, fine grained usage of travis VMs, travis pipeline cleaning

### ISSUE THREAD

**Issue by TotoGaz** [GEOS-DEV/GEOS#2029]
It appears that we were not using the VM sizes we were paying `travis-ci` for.

- [x] Use the `large` machines for all the `travis` pipeline. Done in https://github.com/GEOSX/GEOSX/pull/2025
- [x] Rollback all the azure-pipeline actions: `git` history will allow to get back to the files if we want to go back to it. Done in https://github.com/GEOSX/GEOSX/pull/2025
- [x] We could add the `check_pr_is_assigned` in its own initial step such that we do not initiate jobs for nothing (100% waste). Done in https://github.com/GEOSX/GEOSX/pull/2053
- [x] https://config.travis-ci.com/explore offers an interactive way to test the `.travis.yaml` file, so we should endeavor to remove the warnings or informative messages (it should be a tiny action). Done in https://github.com/GEOSX/GEOSX/pull/2053
- [x] Try to use specific sizes for each steps (tipically, `check` steps sould run on `medium` VMs, and maybe running the GPUs on `x-large`?). I'm not sure that it's indeed possible, but https://config.travis-ci.com/explore seemed to consider it as an option, so let's try 🤞

**Comment by bmhan12** [comment]
> Try to use specific sizes for each steps...

Yes, a [github search](https://github.com/search?q=filename%3A.travis.yml+large) shows size can be adjusted for each job launch.

**Comment by TotoGaz** [comment]
I think we should rush https://github.com/GEOSX/GEOSX/pull/2025 for immediate relief of our build queues (tick box one).
Maybe we can merge it as is and do a better cleaning after?

**Comment by TotoGaz** [comment]
@rrsettgast I'm trying to finish the last tick box.
Whatever I may do in the config file, I stick to `large` VMs.

Do you think we could ask the travis support to stop our specific VM choice so we may be able to better configure them?
According to our current `.travis.yml`, it should be equivalent and seamless.

Actually, even if this does not allow a fine grain configuration, I also prefer relying on explicit documentation than on hidden backend configurations.

**Comment by rrsettgast** [comment]
The use of larger VM's did not work.

**Comment by TotoGaz** [comment]
> The use of larger VM's did not work.

I know:

> Whatever I may do in the config file, I stick to large VMs.

But is it because the `travis` support imposes a specific VM size like they used to do when we couldn't chose the VM sizes ? Or is it because it's impossible?

**Comment by TotoGaz** [comment]
Also, IIRC, I could not downsize a VM, which really surprises me and makes me think there's something else.
Downsizing should really work.

**Comment by TotoGaz** [comment]
Questions related to travis are not more relevant 😉
