### ISSUE TITLE
Fail compilation in debug mode on pangea3 with gcc/openmpi

### ISSUE THREAD

**Issue by XL64** [GEOS-DEV/GEOS#2068]
**Describe the bug**
Build failed in debug mode on pangea3

**To Reproduce**
1. Load the modules indicated in pangea3 host config 
2. Build GEOSX with that host-config

**Expected behavior**

**Screenshots**
```
/appli_RD/ACS/pangea_co/workspace/GEOSX/03_GEOSX_checkout_PR/src/coreComponents/LvArray/src/indexing.hpp(194): error: calling a __host__ function("LvArray::ArrayOfSets<int, int,  ::LvArray::ChaiBuffer> ::ArrayOfSets") from a __host__ __device__ function("") is not allowed

/appli_RD/ACS/pangea_co/workspace/GEOSX/03_GEOSX_checkout_PR/src/coreComponents/LvArray/src/indexing.hpp(194): error: calling a __host__ function("LvArray::ArrayOfSets<int, int,  ::LvArray::ChaiBuffer> ::ArrayOfSets") from a __host__ __device__ function("") is not allowed

2 errors detected in the compilation of "/appli_RD/ACS/pangea_co/workspace/GEOSX/03_GEOSX_checkout_PR/src/coreComponents/mesh/EdgeManager.cpp".
```
**Platform (please complete the following information):**
- Machine: Pangea3
- Compiler: [gcc 8.4.1
- GEOSX Version develop
**Additional context**

**Comment by TotoGaz** [comment]
Do you have the command line that fails?

**Comment by XL64** [comment]
Yes : `make -C /scratch/users/j0489939/builds-jenkins/geosx/build/origin/develop-54-15d221c45e87e60f7982630319a2e0a8dd7cd141-PR-2032/build-pangea3-gcc8.4.1-openmpi-4.1.2-debug`
It's launch within my Jenkins. Not sure if it passed before or if I never checked it correctly... I didn't find any working log.

**Comment by TotoGaz** [comment]
I mean, do you know which file is not compiling?

**Comment by XL64** [comment]
Yes it's /src/coreComponents/mesh/EdgeManager.cpp

**Comment by TotoGaz** [comment]
@XL64 Is this still relevant?
