### ISSUE TITLE
Simplify definition of regions in the XML

### ISSUE THREAD

**Issue by jeannepellerin** [GEOS-DEV/GEOS#2223]
**What is the requested feature?**
As a user, I want to define easily regions from their name in the subsurface model.

A non exhaustive list of subitems are:
   - the different cell types are managed by GEOSX 
   - the user manages  meaninful regions names that correspond to the subsurface model instead of an Attribute value
   - the user can create regions that do not have a physical meaning (rock type, fluid type) but e.g. border between countries
   

**Is your request related to a specific problem?**
The XML file is very complex to write and there is no check of its validity.
GEOSX might crash without notice and no error message.

**Describe the solution you'd like**
Check of validity of the XML 
Clear error messages to the user
Replace entries that have a meaning for the developers by entries that have a meaning for the users to define Regions

**Comment by AntoineMazuyer** [comment]
Great suggestion.

Using the VTU/VTK file there is unfortunately no way to associate an `attribute` id with a name... except using VTM structure BUT in my opinion, it will add complexity for users to build the mesh (need to respect a certain hierarchy, naming convention etc...).

One solution could be to provide a map `attribute id <--> name` that can be either communicate to geosx through an external file `map.txt` or in the vtu file (adding a new XML tag)

**Comment by untereiner** [comment]
If I can summarize (do not hesitate to correct me):

- pure vtk solution:
  - With VTU files: add an attribute per region with the name of that region (add a null value to the elements not concerned by the region): memory overhead but keeps a simple format
  - With VTM files: same as above with less memory overhead but hierarchical format

- deck oriented solution:
  - As @AntoineMazuyer wrote, add somehow a map in the deck: new file as a dependency, consistency needs to be tracked.
  
- RESQML solution:
  - Already possible with SubRepresentations (flexible use and memory efficient) but puts the effort to the modelling software.
