### ISSUE TITLE
Misleading Error Message - missing cell block name in CellElementRegion specification

### ISSUE THREAD

**Issue by philippechehade** [GEOS-DEV/GEOS#2242]
When trying to import a grid the below error was received : 

***** ERROR
***** LOCATION: /tmp/GEOSX/src/coreComponents/mesh/FaceManager.cpp:199
***** Controlling expression (should be false): true
***** Rank 131: Face 0 is not connected to an element

The problem was solved by adding the keyword "0_wedges" to the cell block section in the XML. 
However, the main issue is that the error presented lead us to think that the grid had problems, whereas the problem was solved in the XML and not the grid.

Hence as a user I would have preferred to have a clear message on where the problem is coming from.
Moreover, it is still not clear for me, as a user, to understand the need in defining the cell types for the different regions in the XML when GeosX can detect these types automatically. 

For a model with 20 regions, it is very time consuming, and makes it hard for the user to detect where the problem is coming from. 

Version used: 490f777
@jeannepellerin

**Comment by TotoGaz** [comment]
I may be mistaken but I think that we now have the possibility to define some placeholders and generics in the xml (like `ElementRegions` or `ElementRegions/Region*` etc).

@francoishamon @rrsettgast do you have more precise information?

**Comment by MelReyCG** [comment]
With PR #2450, the following error will be output:
```
***** ERROR
***** LOCATION: /tmp/GEOSX/src/coreComponents/mesh/FaceManager.cpp:199
***** Controlling expression (should be false): true
***** Rank 131: Face 0 is not connected to an element
The cellBlocks of the CellElementRegions might not have referenced this face. 
Be sure to include every primitive of every part of the mesh in the cellBlocks.
```
