### ISSUE TITLE
Mismatch of cell volume computation in GEOSX and MeshDoctor

### ISSUE THREAD

**Issue by jeannepellerin** [GEOS-DEV/GEOS#2253]
The python script MeshDoctor in charge of checking that all cells have a positive volume uses a VTK based computation (barycentric subdivision into tetrahedra) while cell volume computation in GEOSX seems to be based on FE transform.

Comparing the elementVolume (from GEOSX) and the Volume computed by VTK in Paraview we found significant differences for pyramids, and hexahedra.
The more distorted the cell, the larger the difference (up to 5% on good looking pyramid in a toy model up to 5000% on a real case)

![volume_mismatch](https://user-images.githubusercontent.com/48675268/215156547-74297fe5-754f-4e25-b68b-470e7681534d.png)

@TotoGaz

**Comment by TotoGaz** [comment]
Thanks for the information @jeannepellerin 
`mesh_doctor` directly uses the VTK volume computation implementation.
So we must investigate the origin of this discrepancy!

**Comment by TotoGaz** [comment]
Hi @margauxraguenel thanks for the comprehensive study, it's very clear.
I will surely switch the computation method.

Though, I'd like to say that the `vtkCellSizeFilter` provides results for all the cell types, while `vtkMeshQuality` only offers information for tets, hexs, wedges, pyramids. Nothing for prims for example.
This is why I selected `vtkCellSizeFilter` over `vtkMeshQuality`.

I'll be able to select the appropriate data from those two filters, it's not an issue, but do you have data for prisms, for example?

**Comment by margauxraguenel** [comment]
Hello @TotoGaz ,

I finally did some tests on a mesh with prisms : 
[smallpebi.vtu.txt](https://github.com/GEOSX/GEOSX/files/10922900/smallpebi.vtu.txt)

As you said, `MeshQuality` is not available for these cells, so I compared the volumes computed by our IX preprocessing code, `CellSizeFilter` and the volume computed by GEOSX.
The results are quite similar : 
![image](https://user-images.githubusercontent.com/32702400/223778080-9d6fc3cf-0a5f-4715-b0a0-fe9198265011.png)
(x axis is volume and y axis is number of cell per volume range)
So `vtkCellSizeFilter` seems to be the one to chose for this type of cell in mesh_doctor.

Hope it helps.

**Comment by TotoGaz** [comment]
Great, thank you for the information!

**Comment by TotoGaz** [comment]
Hello @margauxraguenel this discrepancy should be managed when #2274 gets merged.

**Comment by jeannepellerin** [comment]
Thank you @TotoGaz !
