### ISSUE TITLE
MPI communications for high-order methods on general meshes not working

### ISSUE THREAD

**Issue by sframba** [GEOS-DEV/GEOS#2255]
**Describe the bug**
Starting last year, GEOSX allows to input high-order numerical methods such as the Spectral Element method (SEM). However, if the order is above `1`, the MPI communications are still incomplete, and the numerical scheme cannot be run in parallel.

**To Reproduce**
Create a wave propagation simulation deck using any wave propagation solver (e.g., `AcousticWavePropagationSEM`) specifying `formulation="SEM"` and `order="2"` or any other number above `1`. The simulation runs in sequential mode, but crashes when run in parallel, both with the internal mesh generator and with `vtu` mesh files.

**Expected behavior**
The simulation should run and give the same numerical results as the sequential case.

**Platform (please complete the following information):**
- All machines (tested on Pangea3, Pecan, LLNL machines)
- Compiler: all (tested with gcc-8.4.1)
- GEOSX develop version

**Additional context**
Steps to solve:
- [x] correct MPI communications for the internal mesher
- [x] implement corrections for the `vtu` case. Check to see if #2267 addresses this box.
- [ ] create unit smoke tests for higher orders

**Comment by TotoGaz** [comment]
Hello @sframba can you tell us if https://github.com/GEOSX/GEOSX/pull/2267 fixes the second tickbox ("_implement corrections for the vtu case._")

**Comment by sframba** [comment]
Hi @TotoGaz , it works towards that objective as it allows to load fields for higher orders. However we still need to finalize MPI comms. We are working on it, I will use this issue to track our progress

**Comment by cssherman** [comment]
@sframba - any updates on this issue?

**Comment by sframba** [comment]
Hi @cssherman sorry for the delay, this was solved by PR [2313](https://github.com/GEOS-DEV/GEOS/pull/2313). I'm closing the issue.
