### ISSUE TITLE
Update memory statistics table

### ISSUE THREAD

**Issue by victorapm** [GEOS-DEV/GEOS#2304]
**What is the requested feature?**
Add minimum and average (across ranks) memory utilization statistics from umpire and update format of the statistics table.

**Is your request related to a specific problem?**
No

**Describe the solution you'd like**
Here is an example of what we currently have:
```
Umpire          DEVICE sum across ranks: 15293.4 GB
Umpire          DEVICE         rank max:   31.3 GB
Umpire       DEVICE::0 sum across ranks: 15293.4 G
Umpire       DEVICE::0         rank max:   31.3 GB
Umpire            HOST sum across ranks: 7272.2 GB
Umpire            HOST         rank max:   14.7 GB
Umpire HYPRE_DEVICE_POOL sum across ranks: 7178.4 GB
Umpire HYPRE_DEVICE_POOL         rank max:   14.8 GB
Umpire          PINNED sum across ranks:  256.3 GB
Umpire          PINNED         rank max:  589.6 MB
```

This is what I propose:
```
+-------------------+---------------+---------------+---------------+--------------+
|       Umpire Pool |    Min (GB/%) |    Max (GB/%) |    Avg (GB/%) |   Sum (TB/%) |
|                   |    over ranks |    over ranks |      per rank |    all ranks |
+-------------------+---------------+---------------+---------------+--------------+
|            DEVICE |   31.3  (49%) |   31.3  (49%) |   31.3  (49%) |  15.2  (24%) |
|              HOST |   14.7 (2.9%) |   14.7 (2.9%) |   14.7 (2.9%) |   7.2 (2.9%) |
| HYPRE_DEVICE_POOL |   14.8  (23%) |   14.8  (23%) |   14.8  (23%) |   7.1  (13%) |
|            PINNED |  0.589 (0.1%) |  0.589 (0.1%) |  0.589 (0.1%) |   0.3 (0.1%) |
+-------------------+---------------+---------------+---------------+--------------+

```
**Describe alternatives you've considered**
N/A

**Additional context**
Having access to minimum, maximum, and average utilization leads to a better understanding of load balancing.

**Comment by jeannepellerin** [comment]
Yes, this would definitely help.

We could also add the number of ranks in the output log to be able to trace that info more easily.

**Comment by MelReyCG** [comment]
I'm not sure what you're talking about, I don't think I did that myself, I just assigned myself to this issue because I will start working on it soon.

**Comment by TotoGaz** [comment]
Didn't you do
<img width="700" alt="image" src="https://user-images.githubusercontent.com/49004943/222525923-5c860b30-03eb-494e-ba6a-90dfabf972d0.png">
?

**Comment by MelReyCG** [comment]
Yes I did, we moved it. I just filled the fields.

**Comment by paveltomin** [comment]
@MelReyCG any update?
