### ISSUE TITLE
Fix the error in the plot of deviated Poro-Elastic Wellbore Example 2

### ISSUE THREAD

**Issue by sytuannguyen** [GEOS-DEV/GEOS#2322]
**What needs to be documented?**
The validation of GEOSX in the example of deviated Poro-Elastic Wellbore with in-situ stress is now wrong. 

The link to this example is: 

https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/deviatedPoroElasticWellbore/Example2.html

This may due to the modification of the script producing the analytical results. This script need to be corrected to make this validation example valid.

**What sort of documentation would help?**
Advanced validation examples.

**What are the deficiencies of the existing documentation?**
Existing docs need to be improved.

**Additional notes or context**

**Comment by TotoGaz** [comment]
Hello @sytuannguyen did you have a chance to look at this issue? Thanks!

**Comment by sytuannguyen** [comment]
@TotoGaz Thank you, I am fixing it right now.
