### ISSUE TITLE
Configure step fails on Quartz with clang13 - cannot find doxygen

### ISSUE THREAD

**Issue by CusiniM** [GEOS-DEV/GEOS#2328]
**Describe the bug**

**To Reproduce**
Launch config script for clang13 on quartz.

**Screenshots**

![Screen Shot 2023-03-07 at 10 15 37 PM](https://user-images.githubusercontent.com/49037133/223634098-2496d4d3-b24e-4ea3-86fc-54f60fae3f51.png)

**Platform (please complete the following information):**
- Machine LLNL/Quartz
- Cmake: 3.23.1
- Compiler: clang 13.0.0
- GEOS Version 0.2

**Additional context**
The problem only seems to exist. I have compared the clang10 and clang13 host configs and could not see anything that may explain this.

**Comment by rrsettgast** [comment]
There is no clang13 TPL installed on quartz

**Comment by CusiniM** [comment]
ah, I thought we once had said we wanted to force everyone to use clang13 that's why I was trying. Shall we add it?
