### ISSUE TITLE
Field specifications not working for high-order wave propagation

### ISSUE THREAD

**Issue by sframba** [GEOS-DEV/GEOS#2355]
**Describe the bug**
When running a wave propagation simulation at order higher than 1, no FieldSpecification can be given. GEOS exits with the following error:
```
initialPressure: there is/are no set(s) named 'all' under the objectPath 'mesh/FE1/nodeManager
```
This blocks all use of higher order wave propagation.

**To Reproduce**
1. Take the standard wave propagation smoke test,`inputFiles/wavePropagation/acous3D_small_base.xml`
2. Increase the order of the method by changing `order="1"` to `order="2"` in the `FiniteElementSpace` section of the `xml`
3. Also change the object paths of the FIeldSpecification for the variable `initialPressure` as follows: `objectPath="mesh/FE1/nodeManager"`
4. Run the smoke test `inputFiles/wavePropagation/acous3D_abc_fs_smoke.xml` that includes the edited file. `GEOSX` fails with the above error.

**Expected behavior**
The field specifications works and correctly updates the initial pressure values. If all the object paths are correctly updated in the input file, the simulation runs.

**Platform (please complete the following information):**
- All platforms
- `develop` version
 
**Additional context**
Probably a consequence of [PR 2291](https://github.com/GEOSX/GEOS/pull/2291)

**Comment by francoishamon** [comment]
Yes, I know what is going on, I did not have any high-order test to check the boundary condition validation at the time, so I missed this case. Let me have a look
