### ISSUE TITLE
Just killed

### ISSUE THREAD

**Issue by FishYNY** [GEOS-DEV/GEOS#2371]
Hello. I run a simulation recently. The mesh is imported successfully and the simulation could start. But, at the "multiphasePoroelasticityPreEquilibrationStep" task, the simulation just killed. The mesh file is so large with 2362200 elements that I can't upload here. The input.xml is uploaded. 

```
Time: -1e+11s, dt:1e+11s, Cycle: 0
Task `multiphasePoroelasticityPreEquilibrationStep`: at time -100000000000s, physics solver `multiphasePoroelasticity` is set to perform stress initialization during the next time step(s)
Task `solidMechanicsPreEquilibrationStep`: at time -100000000000s, physics solver `linearElasticity` is resetting total displacement and velocity to zero
Task `solidMechanicsPreEquilibrationStep`: at time -100000000000s, solid model `skeleton` is setting inelastic behavior to `ON` on subRegion `1_hexahedra`. 
Task `solidMechanicsPreEquilibrationStep`: at time -100000000000s, solid model `skeleton` is setting inelastic behavior to `ON` on subRegion `2_hexahedra`. 
Task `solidMechanicsPreEquilibrationStep`: at time -100000000000s, solid model `skeleton` is setting inelastic behavior to `ON` on subRegion `3_hexahedra`. 
Task `solidMechanicsPreEquilibrationStep`: at time -100000000000s, solid model `skeleton` is setting inelastic behavior to `ON` on subRegion `4_hexahedra`. 
Task `solidMechanicsPreEquilibrationStep`: at time -100000000000s, solid model `skeleton` is setting inelastic behavior to `ON` on subRegion `5_hexahedra`. 
Task `solidMechanicsPreEquilibrationStep`: at time -100000000000s, solid model `skeleton` is setting inelastic behavior to `ON` on subRegion `6_hexahedra`. 
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  0
Killed

```

[mycaseco2.zip](https://github.com/GEOSX/GEOS/files/11148291/mycaseco2.zip)

**Comment by TotoGaz** [comment]
@FishYNY Can you monitor if you have enough memory to run your simulation?

**Comment by FishYNY** [comment]
Hello, @francoishamon @TotoGaz 
I post the full log.

GEOSX version: 0.2.0 (develop, sha1: bbd1948c0)
  - c++ compiler: gcc 9.4.0
  - MPI version: Open MPI v4.0.3, package: Debian OpenMPI, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020
  - HDF5 version: 1.12.1
  - Conduit version: 0.8.2
  - VTK version: 9.1.0
  - RAJA version: 2022.3.0
  - umpire version: 2022.3.0
  -  adiak version: ..
  - caliper version: 2.8.0
  - METIS version: 5.1.0
  - PARAMETIS version: 4.0.3
  - scotch version: 6.0.9
  - superlu_dist version: 6.3.0
  - suitesparse version: 5.7.9
  - hypre development version: v2.27.0-9-g52802b646 (master)
Adding Solver of type MultiphasePoromechanics, named multiphasePoroelasticity
Adding Solver of type SolidMechanicsLagrangianSSLE, named linearElasticity
Adding Solver of type CompositionalMultiphaseFVM, named twoPhaseFlow
Adding Mesh: VTKMesh, mesh
Adding Geometric Object: Box, sourceG89-4
Adding Geometric Object: Box, sinkG89-1
Adding Geometric Object: Box, sinkG891-7
Adding Geometric Object: Box, sinkG89-5
Adding Geometric Object: Box, sinkG89-9
Adding Geometric Object: Box, sinkG89-10
Adding Geometric Object: Box, sinkG89-11
Adding Geometric Object: ThickPlane, xneg
Adding Geometric Object: ThickPlane, xpos
Adding Geometric Object: ThickPlane, yneg
Adding Geometric Object: ThickPlane, ypos
Adding Geometric Object: Box, zneg
   TableFunction: initCO2CompFracTable
   TableFunction: initWaterCompFracTable
   TableFunction: initTempTable
   TableFunction: waterRelativePermeabilityTable
   TableFunction: gasRelativePermeabilityTable
   TableFunction: waterCapillaryPressureTable
Adding Event: PeriodicEvent, outputs
Adding Event: PeriodicEvent, linearElasticityStatistics
Adding Event: PeriodicEvent, twoPhaseFlowStatistics
Adding Event: PeriodicEvent, solverApplications
Adding Event: PeriodicEvent, restarts
Adding Event: SoloEvent, multiphasePoroelasticityPreEquilibrationStep
Adding Event: SoloEvent, solidMechanicsPreEquilibrationStep
Adding Event: PeriodicEvent, solverApplicationsEquilibration
Adding Event: SoloEvent, multiphasePoroelasticityPostEquilibrationStep
Adding Event: SoloEvent, solidMechanicsPostEquilibrationStep
Adding Output: VTK, vtkOutput
Adding Output: Restart, restartOutput
Adding Object CellElementRegion named domain from ObjectManager::Catalog.
   TableFunction: fluid_phaseModel1_PhillipsBrineDensity_table
   TableFunction: fluid_phaseModel1_PhillipsBrineViscosity_table
   TableFunction: fluid_phaseModel2_SpanWagnerCO2Density_table
   TableFunction: fluid_phaseModel2_FenghourCO2Viscosity_table
   TableFunction: fluid_CO2Solubility_table
VTK `vtkOutput`: found 1 fields to plot in `fieldNames`, in addition to all fields with `plotLevel` smaller or equal to 1.
VTKMesh 'mesh': reading mesh from /home/pku/codes/codes02232023/runfiles/mycase/G891/co2brine/G891Mesh.vtu
  reading the dataset...
  redistributing mesh...
Generating global Ids from VTK mesh
  finding neighbor ranks...
  done!
VTKMesh 'mesh': generating GEOSX mesh data structure
  preprocessing...
  writing nodes...
  writing cells...
Importing cell block 6_hexahedra
Importing cell block 5_hexahedra
Importing cell block 2_hexahedra
Importing cell block 1_hexahedra
Importing cell block 4_hexahedra
Importing cell block 3_hexahedra
  writing surfaces...
  building connectivity maps...
  done!
Number of nodes: 2418432
  Number of elems: 2362200
             C3D8: 2362200
Load balancing:     min     avg     max
(element/rank): 2362200 2362200 2362200
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, domain, 1_hexahedra
mesh/Level0/domain/1_hexahedra/fluid allocated 8 quadrature points
mesh/Level0/domain/1_hexahedra/porousRock allocated 8 quadrature points
mesh/Level0/domain/1_hexahedra/relperm allocated 8 quadrature points
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, domain, 2_hexahedra
mesh/Level0/domain/2_hexahedra/fluid allocated 8 quadrature points
mesh/Level0/domain/2_hexahedra/porousRock allocated 8 quadrature points
mesh/Level0/domain/2_hexahedra/relperm allocated 8 quadrature points
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, domain, 3_hexahedra
mesh/Level0/domain/3_hexahedra/fluid allocated 8 quadrature points
mesh/Level0/domain/3_hexahedra/porousRock allocated 8 quadrature points
mesh/Level0/domain/3_hexahedra/relperm allocated 8 quadrature points
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, domain, 4_hexahedra
mesh/Level0/domain/4_hexahedra/fluid allocated 8 quadrature points
mesh/Level0/domain/4_hexahedra/porousRock allocated 8 quadrature points
mesh/Level0/domain/4_hexahedra/relperm allocated 8 quadrature points
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, domain, 5_hexahedra
mesh/Level0/domain/5_hexahedra/fluid allocated 8 quadrature points
mesh/Level0/domain/5_hexahedra/porousRock allocated 8 quadrature points
mesh/Level0/domain/5_hexahedra/relperm allocated 8 quadrature points
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, domain, 6_hexahedra
mesh/Level0/domain/6_hexahedra/fluid allocated 8 quadrature points
mesh/Level0/domain/6_hexahedra/porousRock allocated 8 quadrature points
mesh/Level0/domain/6_hexahedra/relperm allocated 8 quadrature points
mesh: importing field data from mesh dataset
   TableFunction: equil_1_hexahedra_water_table
   TableFunction: equil_2_hexahedra_water_table
   TableFunction: equil_3_hexahedra_water_table
   TableFunction: equil_4_hexahedra_water_table
   TableFunction: equil_5_hexahedra_water_table
   TableFunction: equil_6_hexahedra_water_table
Time: -1e+11s, dt:1e+11s, Cycle: 0
Task `multiphasePoroelasticityPreEquilibrationStep`: at time -100000000000s, physics solver `multiphasePoroelasticity` is set to perform stress initialization during the next time step(s)
Task `solidMechanicsPreEquilibrationStep`: at time -100000000000s, physics solver `linearElasticity` is resetting total displacement and velocity to zero
Task `solidMechanicsPreEquilibrationStep`: at time -100000000000s, solid model `skeleton` is setting inelastic behavior to `ON` on subRegion `1_hexahedra`. 
Task `solidMechanicsPreEquilibrationStep`: at time -100000000000s, solid model `skeleton` is setting inelastic behavior to `ON` on subRegion `2_hexahedra`. 
Task `solidMechanicsPreEquilibrationStep`: at time -100000000000s, solid model `skeleton` is setting inelastic behavior to `ON` on subRegion `3_hexahedra`. 
Task `solidMechanicsPreEquilibrationStep`: at time -100000000000s, solid model `skeleton` is setting inelastic behavior to `ON` on subRegion `4_hexahedra`. 
Task `solidMechanicsPreEquilibrationStep`: at time -100000000000s, solid model `skeleton` is setting inelastic behavior to `ON` on subRegion `5_hexahedra`. 
Task `solidMechanicsPreEquilibrationStep`: at time -100000000000s, solid model `skeleton` is setting inelastic behavior to `ON` on subRegion `6_hexahedra`. 
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  0
Killed

**Comment by paveltomin** [comment]
@FishYNY please provide an update

**Comment by FishYNY** [comment]
You are right. Actually, my device does not have enough memory to run this case.
