### ISSUE TITLE
Errors happen when building in the third-party libraries

### ISSUE THREAD

**Issue by FishYNY** [GEOS-DEV/GEOS#2373]
I downloaded and builded the GEOSX on the HCP which in centos 7 system. Errosrs happen when building in the third-party libraries. I have downloaded hdf5 in my system. I don't kown where is going wrong.

[ 11%] Performing configure step for 'hdf5'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking shell variables initial values... done
checking if basename works... yes
checking if xargs works... yes
checking for cached host... none
checking for config x86_64-unknown-linux-gnu... no
checking for config x86_64-unknown-linux-gnu... no
checking for config unknown-linux-gnu... no
checking for config unknown-linux-gnu... no
checking for config x86_64-linux-gnu... no
checking for config x86_64-linux-gnu... no
checking for config x86_64-unknown... no
checking for config linux-gnu... found
compiler '/gpfs/share/home/2101112002/software/miniconda3/bin/mpicc' is GNU gcc-12.2.0
compiler 'mpif90' is GNU gfortran-4.8.5
compiler '/gpfs/share/home/2101112002/software/miniconda3/bin/mpicxx' is GNU g++-12.2.0
checking for config ../hdf5/config/site-specific/host-sk1-data01.hpc.pku.edu.cn... no
checking for config ../hdf5/config/site-specific/host-hpc.pku.edu.cn... no
checking for config ../hdf5/config/site-specific/host-pku.edu.cn... no
checking for config ../hdf5/config/site-specific/host-edu.cn... no
checking for config ../hdf5/config/site-specific/host-cn... no
checking for clang sanitizer checks... checking build mode... production
checking for gcc... /gpfs/share/home/2101112002/software/miniconda3/bin/mpicc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/gpfs/share/home/2101112002/codes04022023/thirdPartyLibs/build-your-platform-release/hdf5/src/hdf5-build':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
make[2]: *** [hdf5/src/hdf5-stamp/hdf5-configure] Error 1
make[1]: *** [CMakeFiles/hdf5.dir/all] Error 2
make: *** [all] Error 2

[config.log](https://github.com/GEOSX/GEOS/files/11154637/config.log)

**Comment by untereiner** [comment]
Have you made some progress compiling the third parties ?

**Comment by untereiner** [comment]
Same as for #2388 ? @FishYNY

**Comment by paveltomin** [comment]
@FishYNY please provide an update or close the issue
