### ISSUE TITLE
Multi-phase EOS solver

### ISSUE THREAD

**Issue by ver2king** [GEOS-DEV/GEOS#2379]
Within GEOSX, I saw that the EOSsolvers are available for the CO2-H2O system. Following the codes, I also saw the calculations for the density & viscosity. The code I mentioned is in the file below:

https://github.com/GEOSX/GEOS/blob/cadc47703f3936f8cff304a10c7ece9168b4c3cc/src/coreComponents/constitutive/fluid/PVTFunctions/CO2EOSSolver.hpp

However, for other possible multi-component systems (e.g., hydrocarbon-CO2), I only found .hpp files to define such systems and no other files that are relevant to the EOS solvers.

Therefore, please raise a continual discussion here, if I miss the EOSsolver files within GEOSX for multi-component systems, or verify the fact that the solver has not been available in GEOSX.

Note: I readily posted this under the discussion, however, there has been no response. In addition, I found the PVTpackage available, however, I could not link the use of this package and GEOS.

**Comment by francoishamon** [comment]
Hello @ver2king 
We are working on this: please check our workplan detailed here https://github.com/GEOS-DEV/GEOS/issues/2465
It will take a few months before it can be used in a simulation, but it will cover the use case you mentioned (CO2 in hydrocarbon systems).
I am closing this issue and I encourage you to check back in a few months.
