### ISSUE TITLE
Unit Test failed to compile on quartz

### ISSUE THREAD

**Issue by acitrain** [GEOS-DEV/GEOS#2399]
**Describe the bug**
I tried to compile develop on quartz using clang 10.0.0 but on unit test from LvArray (testInput.cpp)  failed to compile due to an unused variable. 

**To Reproduce**
1. Configure on quartz using configs/LLNL/quartz-clang@10.0.0.cmake in Release mode
2. Do make -j16
3. Compilation error will occur when compiling testInput.cpp: 
GEOSX/src/coreComponents/LvArray/unitTests/testInput.cpp:19:12: error: unused variable 'IGNORE_OUTPUT' [-Werror,-Wunused-const-variable]
const char IGNORE_OUTPUT[] = ".*";

**Expected behavior**
Code should compile

**Platform**
- Machine: Quartz
- Compiler: clang 10.0.0
- GEOSX Version: 0.2

**Comment by paveltomin** [comment]
@acitrain please close if you don't have the issue anymore
