### ISSUE TITLE
Update Schema Installation

### ISSUE THREAD

**Issue by cssherman** [GEOS-DEV/GEOS#2408]
**What is the requested feature?**
Some of the xml processing scripts refer to the GEOS schema located in the source tree.  Moving forwards, we should properly install the schema and refer to this new location.

**Comment by TotoGaz** [comment]
For reference, some work about deploying the `schema` was done in https://github.com/GEOS-DEV/GEOS/pull/2278.

**Comment by cssherman** [comment]
> For reference, some work about deploying the `schema` was done in #2278.

Thanks - I was aware of this, but was able to find the PR number!
