### ISSUE TITLE
Problem with the mesh input

### ISSUE THREAD

**Issue by khazali** [GEOS-DEV/GEOS#2424]
Hi,

I am currently working on a case that can be found [here](https://github.com/khazali/GeosxIssue).

The case was run with:

- Intel(R) Xeon(R) CPU E5-2690 with 256GB RAM
- Ubuntu 22.04.2 LTS
- GCC 11.3.0 + Intel MKL 2023.0.0 + Open MPI 4.1.2
- GEOS version:  [3fd5fcf](https://github.com/GEOS-DEV/GEOS/commit/3fd5fcfef322ee6569b5d4070027e52cb5d8eb84)

During the execution of the program, it stops in the middle of reading the mesh file, erroneously reporting that some grid cell has a negative volume. The reported grid number (with supposedly negative volume) changes in each run.

**Comment by TotoGaz** [comment]
In case a more recent version of GEOS does not solve the issue, you can check the volumes with [`mesh_doctor`](https://github.com/GEOS-DEV/GEOS/blob/develop/src/coreComponents/python/modules/geosx_mesh_doctor/mesh_doctor.py)

**Comment by khazali** [comment]
The new version cannot be compiled. It gives me the following error during make:

`geos-dev/src/coreComponents/mesh/generators/CellBlockManager.cpp:309:42: error: 'const struct geos::NodesAndElementOfFace' has no member named 'numNodes'
  309 |       GEOS_ASSERT_EQ( numNodesInFace, f0.numNodes );`

**Comment by khazali** [comment]
> A fix has been proposed. Are you able to compile a more recent version and use `mesh_doctor` ?

Many thanks for your guidance and consideration. The problem was a grid generation module that I used but did not write. I have implemented my module and the problem went away.
Thanks again.
