### ISSUE TITLE
Issue with Python and CMake version < 3.18

### ISSUE THREAD

**Issue by untereiner** [GEOS-DEV/GEOS#2431]
**Describe the bug**
At configure step:

```
- Not building pygeosx.
CMake Error at /cmake-3.17.3/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:261 (message):
  No REQUIRED_VARS specified for FIND_PACKAGE_HANDLE_STANDARD_ARGS()
Call Stack (most recent call first):
  /cmake-3.17.3/share/cmake-3.17/Modules/FindPython/Support.cmake:2437 (find_package_handle_standard_args)
  /cmake-3.17.3/share/cmake-3.17/Modules/FindPython3.cmake:309 (include)
  cmake/thirdparty/SetupGeosxThirdParty.cmake:772 (find_package)
  cmake/CMakeBasics.cmake:49 (include)
  CMakeLists.txt:48 (include)

```

The problem comes with #2265 and the find of python even if `ENABLE_PYGEOSX` is `OFF` in `SetupGeosxThirdParty.cmake`.
Given that [cmake issue](https://gitlab.kitware.com/cmake/cmake/-/issues/20655)  (corrected with cmake v3.18) an empty REQUIRED is necessary.

**To Reproduce**
clone and launch cmake on Pangea2

**Platform (please complete the following information):**
- Machine Pangea2 
- Compiler:  gcc 8.3.0
- GEOSX Version: develop
- CMake version: 3.17.3

**Comment by XL64** [comment]
Same for me, it needs to remove the version range in the find_package()
