### ISSUE TITLE
Problem in compilation

### ISSUE THREAD

**Issue by khazali** [GEOS-DEV/GEOS#2432]
Hi,
I have a problem with the compilation of the most recent development version. It gives me the following error during make:

`geos-dev/src/coreComponents/mesh/generators/CellBlockManager.cpp:309:42: error: 'const struct geos::NodesAndElementOfFace' has no member named 'numNodes'`
`309 |       GEOS_ASSERT_EQ( numNodesInFace, f0.numNodes );`

The code is compiled on:

- Intel(R) Xeon(R) CPU E5-2690 with 256GB RAM
- Ubuntu 22.04.2 LTS
- GCC 11.3.0 + Intel MKL 2023.0.0 + Open MPI 4.1.2

_Originally posted by @khazali in https://github.com/GEOS-DEV/GEOS/issues/2424#issuecomment-1539984540_

**Comment by untereiner** [comment]
Try to compile in Release to avoid this assertion. The member doesn't exist and should be corrected!
