### ISSUE TITLE
Error message for wrong porosity range

### ISSUE THREAD

**Issue by RayEGU** [GEOS-DEV/GEOS#2505]
Hello Everyone,

We were working on a CO2 injection model in a tetrahedral grid with one injection well.
This case was run with:

- PANGEA-2 machine

- gcc 8.3.0 compiler

- the Geos version 2e19665

Even though the porsity was wrong (2.5 actually instead of 0.25), the run on Geos worked.
So, as users a error message would be a great help for wrong porosity range.
You'll find below our simulation  folder  (the logs "job_GEOS_954119.out" is for Porosity=2.5 and "job_GEOS_513781.out" for porosity =0.25).
[Test1.zip](https://github.com/GEOS-DEV/GEOS/files/11636365/Test1.zip)

**Comment by francoishamon** [comment]
Hi @RayEGU 
Thanks for reporting this. PR https://github.com/GEOS-DEV/GEOS/pull/2508 will add a warning message when the porosity is above 1 at the beginning of the simulation (number of cells with a porosity above 1, value of max porosity).
