### ISSUE TITLE
Model with 3 wells does not converge at second time step 

### ISSUE THREAD

**Issue by RayEGU** [GEOS-DEV/GEOS#2529]
Hi all,

We're working on a CO2 injection model in a tetrahedral grid with 3 injectors : Well 1 has 3 perforations, 2 perforations for Well 2 and 5 perforations for Well 3.
This case was run with:

- PANGEA-2 machine

- gcc 8.3.0 compiler

We noticed at the second time-step (t=100s)  that the solutions nonconverged and the well control of Well 3 switcthed from rate constraint to BHP constraint, then from  BHP constraint to total volumetric rate constraint. Even though we changed the BHP from 1000 bars to 8000 bars, we got the same results of non convergence. 
 Here is the simulation folder with the log file " job_GEOS_256168.out"
[TestWell.zip](https://github.com/GEOS-DEV/GEOS/files/11755958/TestWell.zip)

**Comment by RayEGU** [comment]
@dkachuma , thanks for the tips. I changed the permeability to 1000 mD for all the model and increased the porosities too. Then, the BHP reference elevation was set to 396.646 m. So, I got some issues :

1. for MPI rank number n = 1 and in surface conditions (useSurfaceConditions = "1", surfacePressure="101325", surfaceTemperature="288.71"), when I increased the flowrate  from 0.03 sm3/s  to   { 0.3; 3; 30; 10,000; 50,000 or 100,000} sm3/s, Geos works very well. But, when I switch to  reservoir conditions (useSurfaceConditions = "0"), Geos works just for the flowrates { 0.03; 0.3; 3} rm3/s, and I got the error "Floating point exception " for the flowrates { 15; 30; 50} rm3/s
 
2. for MPI rank number = 16, and when the  wells are discretised in function of perforations number, Geos works in the case of surface conditions but not in reservoir conditions case for a flowrate =30 m3/s.

PS: I adapted the  targetBHP depending on tests.

**Comment by dkachuma** [comment]
@RayEGU Can I please confirm that the nature of the problem has changed? You're now getting a floating point exception when you use reservoir conditions at higher flow rates? But the convergence problems are not being encountered anymore?

**Comment by paveltomin** [comment]
@RayEGU ?
