### ISSUE TITLE
Failure to compile HypreInterface with ENABLE_HYPRE_DEVICE "CUDA" option

### ISSUE THREAD

**Issue by MedAdh42** [GEOS-DEV/GEOS#2547]
**Compilation error**

Compiling hypreInterface with ENABLE_HYPRE_DEVICE "CUDA" option throws the following errors:

/home/medadh42/dev/sim/GEOSX/src/coreComponents/linearAlgebra/interfaces/hypre/HypreInterface.cpp(45): error: class "hypre_Handle" has no member "device_data"

/home/medadh42/dev/sim/GEOSX/src/coreComponents/linearAlgebra/interfaces/hypre/HypreInterface.cpp(45): error: identifier "hypre_DeviceDataSpgemmUseVendor" is undefined

**To Reproduce**
Used the following config:

site_name(Ubuntu-22.04)

set(CMAKE_C_COMPILER "/usr/bin/gcc" CACHE PATH "")
set(CMAKE_CXX_COMPILER "/usr/bin/g++" CACHE PATH "")
set(CMAKE_Fortran_COMPILER "/usr/bin/gfortran" CACHE PATH "")
set(ENABLE_FORTRAN ON CACHE BOOL "" FORCE)

set(ENABLE_MPI ON CACHE PATH "")
set(MPI_C_COMPILER "/usr/bin/mpicc" CACHE PATH "")
set(MPI_CXX_COMPILER "/usr/bin/mpicxx" CACHE PATH "")
set(MPI_Fortran_COMPILER "/usr/bin/mpifort" CACHE PATH "")
set(MPIEXEC "/usr/bin/mpirun" CACHE PATH "")

set(CMAKE_CUDA_COMPILER "/usr/local/cuda-11.8/bin/nvcc" CACHE PATH "" FORCE)
set(CUDA_TOOLKIT_ROOT_DIR "/usr/local/cuda-11.8/" CACHE STRING "")
set(ENABLE_CUDA ON CACHE BOOL "" FORCE)
set(ENABLE_HYPRE_DEVICE "CUDA" CACHE STRING "" FORCE)
set(CUDA_ARCH "sm_86" CACHE STRING "")
set(CMAKE_CUDA_ARCHITECTURES "86" CACHE STRING "")
set(CMAKE_CUDA_STANDARD 14 CACHE STRING "")
set(CMAKE_CUDA_FLAGS "--expt-extended-lambda" CACHE STRING "")

set(ENABLE_GTEST_DEATH_TESTS ON CACHE BOOL "" FORCE)
set(ENABLE_CALIPER ON CACHE BOOL "")

set(GEOSX_TPL_DIR "/home/medadh42/dev/sim/thirdPartyLibs/install-ubuntu22cuda11-release" CACHE PATH "" FORCE)
include(${CMAKE_CURRENT_LIST_DIR}/tpls.cmake)

**Expected behavior**
No compilation errors.

.

**Platform:**
- Machine : WSL2 Ubuntu-22.04 virtual machine on Windows 11
- Compiler: gcc 11.3.0
- CUDA Version: 11.8.0
- GEOSX Version: 0.2

**Additional context**

**Comment by wrtobin** [comment]
There is a bug in our TPLs repo here:
https://github.com/GEOS-DEV/thirdPartyLibs/blob/master/CMakeLists.txt#L770

We started transitioning from this TPLs build strategy to Spack during my HIP/ROCM work, which also included changing the `ENABLE_HYPRE_CUDA` to `set(ENABLE_HYPRE_DEVICE CUDA STRING CACHE "")`. 

Unfortunately I forgot to propagate the change to the TPLs repo as it wasn't being used for the HIP builds.

If you change that line to `if( ENABLE_HYPRE_DEVICE STREQUAL CUDA)` and reinstall the Hypre TPL it should install appropriately with CUDA support.

**Comment by wrtobin** [comment]
You could try specifying both if you don't won't to change that line.
In your host-config:
`set(ENABLE_HYPRE_DEVICE CUDA CACHE STRING "" )`
`set(ENABLE_HYPRE_CUDA TRUE CACHE BOOL "" )`

**Comment by wrtobin** [comment]
Regardless a bugfix for the TPLs should be forthcoming shortly.

**Comment by MedAdh42** [comment]
Thank you for the responses. I've tried your proposed solutions and indeed it get no compilation errors.
But 21 tests failed and they all seem to have one thing in common (memory acces errors). see the logs file below. 

[LastTest.log](https://github.com/GEOS-DEV/GEOS/files/11879615/LastTest.log)

**Comment by MedAdh42** [comment]
Non the less there is a problem with MPI it does not work even with 1 rank, always the same error:

 [for 1 MPI rank]
CUDA ERROR (code = 101, invalid device ordinal) at memory.c:182

[4 MPI ranks]
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
