### ISSUE TITLE
Suppress travis-ci: move to Github Actions

### ISSUE THREAD

**Issue by TotoGaz** [GEOS-DEV/GEOS#2578]
- [x] Use GHA on the main repository https://github.com/GEOS-DEV/GEOS
_Done in https://github.com/GEOS-DEV/GEOS/pull/2400 and https://github.com/GEOS-DEV/GEOS/pull/2571_
- [x] Use GHA on the TPL repository https://github.com/GEOS-DEV/thirdPartyLibs
_Done in https://github.com/GEOS-DEV/thirdPartyLibs/pull/225_
- [x] Remove `travis` from the TPL
_Done in https://github.com/GEOS-DEV/thirdPartyLibs/pull/235_

**Comment by TotoGaz** [comment]
Can we consider this done?

**Comment by bmhan12** [comment]
Yes!
