### ISSUE TITLE
Don't understand the Geometry session after reading the tutorial

### ISSUE THREAD

**Issue by miraboreasumr** [GEOS-DEV/GEOS#2586]
Hi,

I create a cubic tetra mesh using Gmsh and export it as .VTK
I found in the 3D_10x10x10_compressible_tetra_gravity_base.xml
```
  <Geometry>
    <Box
      name="left"
      xMin="{ -1, -1, -1 }"
      xMax="{ 0.9, 11, 11 }"/>
  </Geometry>
```
This won't work for my mesh,  so what is the idea of creating sets using this Geometry

Thank you

**Comment by jhuang2601** [comment]
@miraboreasumr In this example, the box is used to define a surface to apply pressure boundary condition:
```
    <FieldSpecification
      name="boundaryPressure"
      objectPath="faceManager"
      fieldName="pressure"
      scale="1.1e6"
      setNames="{ left }"/>
```
In your mesh, you need to adjust the coordinates (xMin and xMax) to identify such surface(s), which could be any of the outer surface (top, bottom, left or right).
