### ISSUE TITLE
Need of GA nightly tests to get GCP bundles tagged with last `develop` commit sha

### ISSUE THREAD

**Issue by jafranc** [GEOS-DEV/GEOS#2607]
**Describe the bug**
In our automated deployment script on Sherlock, we use binaries that are auto-uploaded into GCP bucket after successful ~CI/CD~ Nightly. To fetch the latest commit sha from github we use something like:

```
curl -fsSL -H "Accept: application/vnd.github+json" https://api.github.com/repos/GEOS-DEV/GEOS/branches/develop |  jq -r ".commit.sha"
```

Though looking at [CI/CD report](https://github.com/GEOS-DEV/GEOS/actions/runs/5671210622/job/15367851960#step:7:4) I see that for instance for #2588 the generated name from ` GEOSX_EXPORT_DIR=GEOSX-and-TPL-$***GITHUB_SHA:0:7***` is `Copying file:///tmp/GEOSX-and-TPL-611031a.tar.gz`

 Would it be possible to revert to the commit on develop ?
 
 **Reproducer**
 
 Can also be checked for older merged PR #2481 where generated name is `Copying file:///tmp/GEOSX-and-TPL-8d66b52.tar.gz` while commit on develop is (f364f8b)
 seen from (report - line 2924)

**Comment by TotoGaz** [comment]
Your process was accessing elements from the nightly builds.
There are no more nightly builds with GHA, we should probably do it again.
The doc is [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule).

**Comment by jafranc** [comment]
I found a workaround (for now) that consist in fetching the PR number from `develop` commit info and then only the last commit used to run successful CI. It goes like this 

```bash
#fetch last PR number
export pr_num=$( curl -fsSL -H "Accept: application/vnd.github+json" https://api.github.com/repos/GEOS-DEV/GEOS/branches/develop | jq -r ".commit.commit.verification.payload" | grep -oE '#([1-9]+)' )
export pr_num=${pr_num:1}

#then last commit on PR which should be all-pass
export commit_hash=$( curl -fsSL -H "Accept: application/vnd.github+json" https://api.github.com/repos/GEOS-DEV/GEOS/pulls/${pr_num} | jq -r ".head.sha" )
export commit_hash=${commit_hash::7}

echo "commit before merge... ${commit_hash:0:7}"
```
Let me know what you think and if you think it is robust or not.
