### ISSUE TITLE
uncrustify package is a zip file but cmake build tries to untar it

### ISSUE THREAD

**Issue by jerwin66** [GEOS-DEV/GEOS#2626]
**Describe the bug**
Following quick start instructions for thirdPartyLibs here: https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/QuickStart.html#compilation
"make" fails because uncrustify was not properly decompressed, it is a zip file but the build process tries to untar it.

**To Reproduce**
follow quick start identified above

python scripts/config-build.py -hc ../GEOS/host-configs/my-config.cmake -bt Release

**Expected behavior**
thirdPartyLib builds correctly

**Additional context**
I was able to work-around the problem by manually unzipping uncrustify and packaging into a .tar.gz file.
edited CMakeLists.txt:
set(UNCRUSTIFY_URL "${TPL_MIRROR_DIR}/uncrustify-401a409.tar.gz")

**Comment by cssherman** [comment]
@jerwin66  - Could you let us know your platform details and cmake version?  Also, can you try the running the build again in case it was a download issue?

**Comment by jerwin66** [comment]
Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
Rocky Linux 8.4
4.18.0-305.19.1.el8_4.x86_64

cmake version cmake-3.27.2-linux-x86_64

Unclear why this broke the first time, but a second attempt in a brand new directory does seem to work.

     src='/bfs1/cnadmin/jperwin/apps/geosx-try2/thirdPartyLibs/tplMirror/uncrustify-401a409.zip'
     dst='/bfs1/cnadmin/jperwin/apps/geosx-try2/thirdPartyLibs/build-icelake-intel-intelmpi-release/uncrustify/src/uncrustify'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done

**Comment by hpverne** [comment]
I had the same problem, tar(1) can't unpack a zip file. 

I haven't yet tried the work-around jerwin66 suggested (unzip & create new tar file).  I guess that will work, but this seems like an obvious bug in the build procedure.

I use cmake version 3.27.6,  RedHat Enterprise Linux 8.

Relevant output:
```
-- extracting...
     src='/uio/kant/geo-geofag-u1/hpverne/GEOS/thirdPartyLibs/tplMirror/uncrustify-401a409.zip'
     dst='/uio/kant/geo-geofag-u1/hpverne/GEOS/thirdPartyLibs/take01/uncrustify/src/uncrustify'
-- extracting... [tar xfz]
CMake Error: Problem with archive_read_open_file(): Unrecognized archive format
CMake Error: Problem extracting tar: /uio/kant/geo-geofag-u1/hpverne/GEOS/thirdPartyLibs/tplMirror/uncrustify-401a409.zip
-- extracting... [error clean up]
CMake Error at uncrustify-stamp/extract-uncrustify.cmake:40 (message):
  Extract of
  '/uio/kant/geo-geofag-u1/hpverne/GEOS/thirdPartyLibs/tplMirror/uncrustify-401a409.zip'
  failed
```
