### ISSUE TITLE
Failing ci tests in Debug mode

### ISSUE THREAD

**Issue by Algiane** [GEOS-DEV/GEOS#2631]
**Describe the bug**
The assertion that `numNodesInFace` is equal to `numNodes` seems erroneous. To my understanding, numNodes is the total number of nodes in mesh while `numNodesInFaces` is the number of nodes per face.
It seems that this assertion has been commented and uncommented multiple times since one year.

**To Reproduce**
1. Build geos in Debug mode
2. Run the `make test` command
3. See failure 

For example the `testDofManager` test fails.

**Expected behavior**
All test should pass in Debug mode (for me it fixes 28 from 30 failing tests).

**Platform (please complete the following information):**
- Machine: Mac M1 Max
- Compiler: Clang 14.0.0
- GEOSX Version: 068dcde698fb4a1a25d6f4ab08066de4e898a5b2

I would suggest to delete this assertion (I will attach a PR for that) and to add at least one github-ci config in Debug mode.

**Comment by Algiane** [comment]
I don't have the rights to create new branches so please find attached a patch containing a fix proposal.
[0001-Remove-1-erroneous-assert-issue-2631.patch](https://github.com/GEOS-DEV/GEOS/files/12402527/0001-Remove-1-erroneous-assert-issue-2631.patch)

Best

**Comment by klevzoff** [comment]
IIRC we discovered at some point that out CI always builds with `-DNDEBUG` which disables most assertions (even in `Debug` builds), and I don't think anyone has come up with a fix yet?

**Comment by Algiane** [comment]
Hi,

Thanks for your help.

If I am not wrong:
  1. hdf5 exports the `NDEBUG` flag in its `HDF5_DEFINITIONS` CMake variable (https://cmake.org/cmake/help/latest/module/FindHDF5.html);
  2. then `conduit` (v0.8.2) registers the hdf5 library using the `blt_register_library` macro and export the content of `HDF5_DEFINITIONS`(see [conduit-0.8.2/src/cmake/thirdparty/SetupHDF5.cmake](https://github.com/LLNL/conduit/blob/72f58ef894cf627d00258e813a43752975e2c02b/src/cmake/thirdparty/SetupHDF5.cmake#L326-L329));
  3. the compilation of conduit generates the `$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/conduit/conduit.cmake` file that exports publicly the `NDEBUG` definition (`INTERFACE_COMPILE_DEFINITIONS` CMake's keyword) in the target properties of `conduit_relay.*` targets;
  4. when building `geos` against `conduit`, the `NDEBUG` flags is finally added when we import the `conduit` definitions.
  
I am not sure why `hdf5` exports the `NDEBUG` flag (for me it seems useless) but I don't think that we have any control over that (I can try to post an issue if you think that it makes sense) so I think that the best solution is to try to do something either at the `geos` level, at the `conduit` level or at the `blt` one.

I have no idea of the implications of changing any part of the compilation process and I am far from being a CMake expert so I would welcome your suggestions.

Maybe we can try to test somewhere it makes sense (probably somewhere in `geos`) the presence of the `NDEBUG` flag when `CMAKE_BUILD_TYPE` is equal to `Debug` to remove this spurious flag ?

Thanks by advance for your help,
Best

**Comment by Algiane** [comment]
Thanks for your feedback @tbeltzun ,

I have submitted an issue to the hdf5 group here: https://github.com/HDFGroup/hdf5/issues/3526.

Best

**Comment by Algiane** [comment]
Hi,

Following the discussion with the hdf5 support, building hdf5 using CMake allows to get rid of this annoying `NDEBUG` flag.
I have submitted a PR in the ThirdPartyLibrary repository to propose a CMake build for hdf5 ([PR#239](https://github.com/GEOS-DEV/thirdPartyLibs/pull/239)).
It should allow to test Geos in `Debug` CMake mode (so without `-DNDEBUG` compiler flag and with the test of the code asserts).

Best

**Comment by Algiane** [comment]
Finally:
  - The issue linked to the spurious NDEBUG flag when testing Geos in Debug mode is solved by:
    - the compilation of hdf5 using CMake instead of Autogen in the ThirdPartyLibraries (PR https://github.com/GEOS-DEV/thirdPartyLibs/pull/243) 
    - the build of Geos against these new TPL build (PR #2700) -> now the build in Debug mode fails as expected
   - the erroneous assert is removed by PR #2699 that fixes the build of #2700.
   
Thank you by advance for reviewing this 3 PRs.
Best
