### ISSUE TITLE
hydraulic fracturing example in the basic examples fails to converge

### ISSUE THREAD

**Issue by zhishuaizhang** [GEOS-DEV/GEOS#2632]
I'm trying to run the hydraulic fracturing example in the basic example of the tutorial: https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/basicExamples/hydraulicFracturing/Example.html

It turns out that GEOS stops converging after about ~6 minutes out of a total of 20 minutes of modeling. I didn't change any parameters in the input files. 

I tested with different nonlinear solver parameters but was not able to solve the problem... I am attaching the log file from running the original example for reference.

Thanks a lot!
[heterogeneousInSitu_benchmark_6_2_3.log](https://github.com/GEOS-DEV/GEOS/files/12423370/heterogeneousInSitu_benchmark_6_2_3.log)

**Comment by zhishuaizhang** [comment]
Hi @frankfeifan Thank you very much for your suggestion! I changed the linear solver in `Hydrofracture` to a direct solver as shown below but was still not able to have the modeling finish running.

```
      <LinearSolverParameters
        solverType="direct"
        preconditionerType="none"/>
```

**Comment by paveltomin** [comment]
anyone is looking into that?

**Comment by paveltomin** [comment]
Two changes in the input seems to help to at least finish the case:

1. Set preconditionerType to mgr here:
```
      <LinearSolverParameters
        solverType="gmres"
        preconditionerType="mgr"/>
```
2. Set meanPermCoefficient to 0 here:
```
      <TwoPointFluxApproximation
        name="singlePhaseTPFA"
        meanPermCoefficient="0.0"/>
```
