### ISSUE TITLE
`readthedocs` does not respect bullet points anymore and latex is broken

### ISSUE THREAD

**Issue by TotoGaz** [GEOS-DEV/GEOS#2633]
Our documentation on `readthedocs` does not respect the bullet points anymore. For example, the code
```
Supported Formats
=================

GEOS provides features to run simulations on unstructured meshes.
It uses VTK_ to read the external meshes and its API to write
it into the GEOS mesh data structure.

The supported mesh elements for volume elements consist of the following:

- 4-node tetrahedra,
- 5-node pyramids,
- 6-node wedges,
- 8-node hexahedra,
- n-gonal prisms (n = 7, ..., 11).

The mesh can be divided in several regions.
These regions are intended to support different physics
```
[generates](https://geosx-geosx.readthedocs-hosted.com/en/latest/coreComponents/mesh/docs/Mesh.html#supported-formats)

![image (7)](https://github.com/GEOS-DEV/GEOS/assets/49004943/c2556d8a-012c-4e7b-a5fd-37563be2a529)

This is true everywhere in the doc, not only for the example I provide.

**Comment by sytuannguyen** [comment]
There is also an issue with the mathematical formulas as shown below:

![image](https://github.com/GEOS-DEV/GEOS/assets/45685596/9434dd00-9695-4e51-a930-ca35416d4728)

**Comment by drmichaeltcvx** [comment]
Have you tried

```
* item 1
* item 2
* item 3
```

* item 1
* item 2
* item 3

or insert html directly

```
<ul>  
 <li>First item</li>  
 <li>Second item</li>  
 <li>Third item</li>  
 <li>Fourth item</li>
</ul>
```
<ul>  
 <li>First item</li>  
 <li>Second item</li>  
 <li>Third item</li>  
 <li>Fourth item</li>
</ul>

https://www.markdownguide.org/basic-syntax/
