### ISSUE TITLE
Errors when running multiple-CPU parallel mode on Ubuntu laptop

### ISSUE THREAD

**Issue by RockistY** [GEOS-DEV/GEOS#2638]
I ran into errors when running tutorials comparing the single CPU mode and multiple-CPU mode. It works for one case but mostly I got the following similar pattern of error messages which make me suspect if my MPI has been installed properly. 

For the successful case I've tried (Stress along a fault - advanced example), I tried single-CPU and multi-CPU run (mpirun -np 4 ... -x 2 -y 2 -z 1). It surprised me the latter taking longer run time than the former. Is it normal?

Trial another tutorial (CO2 injection in Basic Example) following exactly the same instructions from documentation, using: mpirun -np 4 ... -x 1 -y 1 -z 4, I got the following error messages. Other cases I ended up with failure yielded similar error messages like below. I've also tried different combinations of partitions number following the instructions (Nx * Ny * Nz = Nnp).  

I wonder if my MPI is properly set up? How to validate the MPI installation with Geosx?

Thanks
---------------------------------------------------------------------------------------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
TableFunction: fluid_phaseModel2_FenghourCO2Viscosity_table
TableFunction: fluid_CO2Solubility_table
TableFunction: fluid_phaseModel2_FenghourCO2Viscosity_table
TableFunction: wellControls_ConstantBHP_table
TableFunction: wellControls_ConstantTotalRate_table
TableFunction: wellControls_ConstantPhaseRate_table
TableFunction: WellControls_OpenStatus_table
TableFunction: fluid_CO2Solubility_table
TableFunction: wellControls_ConstantBHP_table
TableFunction: wellControls_ConstantTotalRate_table
TableFunction: wellControls_ConstantPhaseRate_table
TableFunction: WellControls_OpenStatus_table
***** ERROR
***** LOCATION: /home/roger/Workspace/GEOSX/GEOS/src/coreComponents/mesh/mpiCommunications/SpatialPartition.cpp:173
***** Controlling expression (should be false): check != m_size
***** Rank 0:
Expected check == m_size
check = 4
m_size = 1

**Comment by paveltomin** [comment]
You can try to follow general Open MPI instructions first https://docs.open-mpi.org/en/v5.0.x/validate.html
