### ISSUE TITLE
Robustness of linear solver wrt time step increase

### ISSUE THREAD

**Issue by paveltomin** [GEOS-DEV/GEOS#2671]
When designing and testing new nonlinear solver strategies, we need to be able to run bigger case (direct linear solver in not an option) with larger time steps (to stress the nonlinear solver).
Currently it is not always possible to do because linear solver starts to struggle leading to maximum linear iterations reached and thus badly affecting the nonlinear solver convergence and spoiling the total CPU time.
Some examples of the observed behavior are below:
![image](https://github.com/GEOS-DEV/GEOS/assets/2421323/d4e2232f-03b8-4988-8b35-6a10b23e30de)
![image](https://github.com/GEOS-DEV/GEOS/assets/2421323/6f63224d-cb93-49c3-b3ef-7b686ed68dc0)
![image](https://github.com/GEOS-DEV/GEOS/assets/2421323/468621a3-1e7d-41c1-8347-eaefe6fb794f)
All cases are from here https://github.com/GEOS-DEV/MAELSTROM/tree/master/usecases/francois

**Comment by victorapm** [comment]
cc @oseikuffuor1

**Comment by paveltomin** [comment]
Performance for SPE10 is better after https://github.com/GEOS-DEV/GEOS/pull/2928
