### ISSUE TITLE
CarmanKozenyPermeability can't be applied

### ISSUE THREAD

**Issue by FishYNY** [GEOS-DEV/GEOS#2744]
Hi.
I just modified the permeability model of the basic case from the input files. But it fail to run. The log information is as follow:
Num ranks: 1
GEOSX version: 0.2.0 (develop, sha1: 94e338c7f)
  - c++ compiler: gcc 9.4.0
  - MPI version: Open MPI v4.0.3, package: Debian OpenMPI, ident: 4.0.3, repo rev: v4.0.3, Mar 03, 2020
  - HDF5 version: 1.12.1
  - Conduit version: 0.8.2
  - VTK version: 9.2.6
  - RAJA version: 2023.6.1
  - umpire version: 2023.6.0
  -  adiak version: ..
  - caliper version: 2.10.0
  - METIS version: 5.1.0
  - PARAMETIS version: 4.0.3
  - scotch version: 7.0.3
  - superlu_dist version: 6.3.0
  - suitesparse version: 5.7.9
  - Python3 version: 3.8.10
  - hypre release version: 2.29.0
Started at 2023-10-08 12:13:01.421200822
Adding Mesh: InternalMesh, mesh
Adding Event: PeriodicEvent, solverApplications
Adding Event: PeriodicEvent, outputs
Adding Solver of type SinglePhaseFVM, named SinglePhaseFlow
Adding Geometric Object: Box, source
Adding Geometric Object: Box, sink
Adding Output: Silo, siloOutput
Adding Object CellElementRegion named mainRegion from ObjectManager::Catalog.
mesh: total number of nodes = 1331
mesh: total number of elems = 1000
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh, Level0, mainRegion, cellBlock
mesh/Level0/mainRegion/cellBlock/water allocated 1 quadrature points
mesh/Level0/mainRegion/cellBlock/rock allocated 1 quadrature points
***** ERROR
***** LOCATION: /home/pku/codes/codes09122023/GEOS/src/coreComponents/common/DataTypes.hpp:100
***** Controlling expression (should be false): ptr == nullptr
***** Rank 0: Cast from geos::constitutive::CarmanKozenyPermeability to geos::constitutive::ConstantPermeability failed.

** StackTrace of 10 frames **
Frame 0: geos::constitutive::ConstantPermeability const& geos::dataRepository::Group::getGroup<geos::constitutive::ConstantPermeability, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const 
Frame 1: geos::constitutive::CoupledSolid<geos::constitutive::NullModel, geos::constitutive::PressurePorosity, geos::constitutive::ConstantPermeability>::initializePreSubGroups() 
Frame 2: geos::dataRepository::Group::initialize() 
Frame 3: geos::dataRepository::Group::initialize() 
Frame 4: geos::dataRepository::Group::initialize() 
Frame 5: geos::dataRepository::Group::initialize() 
Frame 6: geos::ProblemManager::problemSetup() 
Frame 7: geos::GeosxState::initializeDataRepository() 
Frame 8: main 
Frame 9: __libc_start_main 
Frame 10: _start 
=====

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

The input files are as follows
[case.zip](https://github.com/GEOS-DEV/GEOS/files/12840642/case.zip)
:

**Comment by sytuannguyen** [comment]
@FishYNY I would guess that this issue is because you are using `CarmanKozenyPermeability` inside `CompressibleSolidConstantPermeability`. You may want to try with `CompressibleSolidCarmanKozenyPermeability` in place of `CompressibleSolidConstantPermeability`.

**Comment by FishYNY** [comment]
yeah, you are right. Thanks a lot.
