### ISSUE TITLE
How can we calculate the Total CO2 injected? 

### ISSUE THREAD

**Issue by beckyggbbh** [GEOS-DEV/GEOS#2745]
I im still working with the "CO2 Plume Evolution and Leakage Through an Abandoned Well"
(But now with my own parameters) 
Trying to validate the code, I realice that the supossed CO2 inyected (Iny rate*total time) Is not even close to the real that im "storing" calculated by the last saturation * posity * total volume of my model.  

Im taking the last saturation with Paraview.

**Comment by jeannepellerin** [comment]
The total injected CO2 should be available in the log file of GEOS.

**Comment by paveltomin** [comment]
Total injected CO2 is already available with `CompositionalMultiphaseStatistics`
