### ISSUE TITLE
add code coverage metric

### ISSUE THREAD

**Issue by tbeltzun** [GEOS-DEV/GEOS#2746]
**What is the requested feature?**
Uncovered code is guaranteed to break at some point: using the code coverage metric to assess quality of the developed code can be an asset.

**Is your request related to a specific problem?**
As a concrete example, https://github.com/GEOS-DEV/GEOS/issues/2651 happens because the `-m 0` option of GEOS is untested in CI.

**Describe the solution you'd like**
Add CI generated coverage reports (and badge in README.md) to ease development.

**Comment by rrsettgast** [comment]
@tbeltzun Have you worked with the various coverage tools? What coverage tool do you like best?
