### ISSUE TITLE
Math equations' format errors

### ISSUE THREAD

**Issue by sytuannguyen** [GEOS-DEV/GEOS#2761]
**Describe the issue**
Error in the format of math equations as shown below:

![image](https://github.com/GEOS-DEV/GEOS/assets/45685596/e5b84062-0218-46bd-b51e-078471aa2109)

or

![image](https://github.com/GEOS-DEV/GEOS/assets/45685596/0752b59a-6027-499a-b707-ab439414e468)

**Proposed cleanup**

**Additional context**

**Comment by TotoGaz** [comment]
Here's the page https://geosx-geosx.readthedocs-hosted.com/en/latest/coreComponents/constitutive/docs/solid/Theory.html#small-strain-models

**Comment by cssherman** [comment]
Hmmm... It seems like I missed some equations when I was doing my checks.  It seems like the latex "\tensor{}" and "\bm{}" directives aren't standard latex (they are provided by a "tensor" plugin).  I'm looking at pdf docs, which should have this package enabled, and if these do influence how the variables look, the effect is subtle.  

I'd vote for limiting the latex math used in the sphinx docs to the base latex features.  @rrsettgast @TotoGaz - any thoughts?

**Comment by cssherman** [comment]
Otherwise, we could test turning on the `imgmath` sphinx extension again, and see if that resolves the issue

**Comment by TotoGaz** [comment]
If `imgmath` fixes it, let's go.
Otherwise, limiting ourselves to the most common subset of latex's packages seems like a good idea.

Eventually, looks like we need to be able to set a _warning-are-errors_ `rtd` build such that we do not end up unstacking again a bunch of stacked errors all at once?
