### ISSUE TITLE
COMPLIATION ERROR FOR GEOS UBUNTU

### ISSUE THREAD

**Issue by kelvin-hung** [GEOS-DEV/GEOS#2771]
Please describe your issue here.  Try to be as specific as possible.
Dear DEVELOPERS GEOS,

i am  very new for GEOS. I try to compliation as follow this step
**cd thirdPartyLibs
python scripts/config-build.py -hc ../GEOS/host-configs/your-platform.cmake -bt Release
cd build-your-platform-release
make**

I USING THIS COMMAND FOR COMPLIATION'

GEOSX_TPL_DIR=/home/hungccs/codes/thirdPartyLibs--release python3 scripts/config-build.py -hc host-configs/test.cmake -bt Release

However, I FACING AN EORROR.

COULD YOU HELP ME CHECK MY EORR AND MY CMAKE FILE?

[error.txt](https://github.com/GEOS-DEV/GEOS/files/13048687/error.txt)
[](url)

MY TEST.CMAKE AS BELOW
```
# file: test.cmake
# detect host and name the configuration file
site_name(HOST_NAME)
set(CONFIG_NAME "test" CACHE PATH "")
message("CONFIG_NAME = ${CONFIG_NAME}")
# set paths to C, C++, and Fortran compilers. Note that while GEOS does not contain any␣
˓→Fortran code,
# some of the third-party libraries do contain Fortran code. Thus a Fortran compiler␣
→must be specified.
set(CMAKE_C_COMPILER "/usr/bin/clang" CACHE PATH "")
set(CMAKE_CXX_COMPILER "/usr/bin/clang++" CACHE PATH "")
set(CMAKE_Fortran_COMPILER "/usr/local/bin/gfortran" CACHE PATH "")
set(ENABLE_FORTRAN OFF CACHE BOOL "" FORCE)
# enable MPI and set paths to compilers and executable.
# Note that the MPI compilers are wrappers around standard serial
compilers.
# Therefore, the MPI compilers must wrap the appropriate serial
compilers specified # in CMAKE_C_COMPILER, CMAKE_CXX_COMPILER, and
CMAKE_Fortran_COMPILER. set(ENABLE_MPI ON CACHE PATH "")
set(ENABLE_MPI ON CACHE BOOL "")
set(MPI_C_COMPILER "/usr/local/bin/mpicc" CACHE PATH "")
set(MPI_CXX_COMPILER "/usr/local/bin/mpicxx" CACHE PATH "")
set(MPI_Fortran_COMPILER "/usr/local/bin/mpifort" CACHE PATH "")
set(MPIEXEC "/usr/local/bin/mpirun" CACHE PATH "")
# disable CUDA and OpenMP
set(ENABLE_CUDA OFF CACHE BOOL "" FORCE)
set(ENABLE_OPENMP OFF CACHE BOOL "" FORCE)
# enable PVTPackage
set(ENABLE_PVTPackage ON CACHE BOOL "" FORCE)
# enable tests
set(ENABLE_GTEST_DEATH_TESTS ON CACHE BOOL "" FORCE )
# define the path to your compiled installation directory
set(GEOSX_TPL_DIR "/home/hungccs/codes/thirdPartyLibs" CACHE PATH "")
# let GEOS define some third party libraries information for you
include(${CMAKE_CURRENT_LIST_DIR}/tpls.cmake)
```

**Comment by kelvin-hung** [comment]
the error text file is uploaded mistake.

SO i copy my error here"

hungccs@ubuntu:~/codes/thirdPartyLibs$ GEOSX_TPL_DIR=/home/hungccs/codes/thirdPartyLibs--release python3 scripts/config-build.py -hc host-configs/test.cmake -bt Release
[config-build.py]:[INFO]: Using host config file: '/home/hungccs/codes/thirdPartyLibs/host-configs/test.cmake'.
[config-build.py]:[INFO]: Build path is: build-test-release
[config-build.py]:[INFO]: Build directory '/home/hungccs/codes/thirdPartyLibs/build-test-release' already exists. Deleting...
[config-build.py]:[INFO]: Creating build directory '/home/hungccs/codes/thirdPartyLibs/build-test-release'...
[config-build.py]:[INFO]: Install directory '/home/hungccs/codes/thirdPartyLibs/install-test-release' already exists. Deleting...
[config-build.py]:[INFO]: Creating install path '/home/hungccs/codes/thirdPartyLibs/install-test-release'...
[config-build.py]:[INFO]: Extracting cmake entry from host config file /home/hungccs/codes/thirdPartyLibs/host-configs/test.cmake
[config-build.py]:[INFO]: Could not find a cmake entry in host config file. Using ${PATH}.
[config-build.py]:[INFO]: Changing to build directory '/home/hungccs/codes/thirdPartyLibs/build-test-release'
[config-build.py]:[INFO]: Executing cmake line: 'cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/hungccs/codes/thirdPartyLibs/install-test-release -C/home/hungccs/codes/thirdPartyLibs/host-configs/test.cmake /home/hungccs/codes/thirdPartyLibs'
loading initial cache file /home/hungccs/codes/thirdPartyLibs/host-configs/test.cmake
CMake Error at host-configs/test.cmake:7:
  Parse error.  Expected a command name, got unquoted argument with text
  "˓→Fortran".


CMake Error: Error processing file: /home/hungccs/codes/thirdPartyLibs/host-configs/test.cmake
-- Configuring incomplete, errors occurred!

**Comment by klevzoff** [comment]
Your host-config `test.cmake` contains lines that are not marked as comments and are not valid CMake syntax, like
```
˓→Fortran code,
```
(I formatted your initial post with markdown code block for better readability).

Whichever program (text editor) you used to create/copy the file has split comments into multiple lines and inserted additional symbols like `→`. To be valid CMake, each line containing a comment must start with a `#`.

**Comment by kelvin-hung** [comment]
Dear Klevzoff,
I am sorry to ask you again.

How can i fix this error!

hungccs@ubuntu:~/codes/thirdPartyLibs$ GEOSX_TPL_DIR=/home/hungccs/codes/thirdPartyLibs--release python3 scripts/config-build.py -hc host-configs/test.cmake -bt Release
[config-build.py]:[INFO]: Using host config file: '/home/hungccs/codes/thirdPartyLibs/host-configs/test.cmake'.
[config-build.py]:[INFO]: Build path is: build-test-release
[config-build.py]:[INFO]: Build directory '/home/hungccs/codes/thirdPartyLibs/build-test-release' already exists. Deleting...
[config-build.py]:[INFO]: Creating build directory '/home/hungccs/codes/thirdPartyLibs/build-test-release'...
[config-build.py]:[INFO]: Install directory '/home/hungccs/codes/thirdPartyLibs/install-test-release' already exists. Deleting...
[config-build.py]:[INFO]: Creating install path '/home/hungccs/codes/thirdPartyLibs/install-test-release'...
[config-build.py]:[INFO]: Extracting cmake entry from host config file /home/hungccs/codes/thirdPartyLibs/host-configs/test.cmake
[config-build.py]:[INFO]: Could not find a cmake entry in host config file. Using ${PATH}.
[config-build.py]:[INFO]: Changing to build directory '/home/hungccs/codes/thirdPartyLibs/build-test-release'
[config-build.py]:[INFO]: Executing cmake line: 'cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/hungccs/codes/thirdPartyLibs/install-test-release -C/home/hungccs/codes/thirdPartyLibs/host-configs/test.cmake /home/hungccs/codes/thirdPartyLibs'
loading initial cache file /home/hungccs/codes/thirdPartyLibs/host-configs/test.cmake
CONFIG_NAME = test
CMake Error at host-configs/test.cmake:32 (include):
  include could not find requested file:

    /home/hungccs/codes/thirdPartyLibs/host-configs/tpls.cmake


-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The Fortran compiler identification is unknown
CMake Error at CMakeLists.txt:5 (project):
  The CMAKE_C_COMPILER:

    /home/hungccs/codes/bin/clang

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:5 (project):
  The CMAKE_CXX_COMPILER:

    /home/hungccs/codes/bin/clang++

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:5 (project):
  The CMAKE_Fortran_COMPILER:

    /home/hungccs/codes/bin/gfortran

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!

**Comment by paveltomin** [comment]
The error messages are self-explanatory, consult with cmake documentation in case 8f something is still unclear.

**Comment by TotoGaz** [comment]
@kelvin-hung Most likely your configuration file does not point to valid compilers.
Please double check that you've conveniently provided this information.
