### ISSUE TITLE
Export Global Cell Index out to VTK output

### ISSUE THREAD

**Issue by herve-gross** [GEOS-DEV/GEOS#2781]
**What is the requested feature?**
We would like to visualize the Global Cell index used in GEOS by printing these values out as a property on the VTK output.

**Is your request related to a specific problem?**
This is helpful when importing output properties on an input mesh with a different indexing system.

**Describe the solution you'd like**
There is a flag in the XML input file for this feature (`outputGlobalCellsIndex=true` or something equivalent) and the Global Cell index is part of the possible properties to visualize in the VTK output.

**Comment by sytuannguyen** [comment]
I will take this.

**Comment by sytuannguyen** [comment]
Apparently, this can be done by defining the fieldNames="{localToGlobalMap}" in vtkOutput as suggested by @untereiner .

**Comment by herve-gross** [comment]
@fuyuli123456 will this help you?

**Comment by fuyuli123456** [comment]
Yes, this helps!
