### ISSUE TITLE
Modify compositionalMultiphaseWells tests and reactivate "Throw" 

### ISSUE THREAD

**Issue by CusiniM** [GEOS-DEV/GEOS#2786]
Merging https://github.com/GEOS-DEV/GEOS/pull/2552 triggered some integratedTests failure because it required new baselines and because some tests have pressure and temperature that go outside of the allowable bounds.

For now, I have fixed the issue in https://github.com/GEOS-DEV/GEOS/pull/2785 by replacing the `throw` with a warning. @dkachuma, @MelReyCG, we should review the tests that are failing, modify them appropriately, and then reactivate the `throw`.

The tests that are failing are:

````
FAIL RUN   : staircase_co2_wells_hybrid_3d_01                  : compositionalMultiphaseWell/staircase_co2_wells_hybrid_3d_01                       
FAIL RUN   : staircase_co2_wells_3d_08                         : compositionalMultiphaseWell/staircase_co2_wells_3d_08                             
FAIL RUN   : staircase_co2_wells_3d_01                         : compositionalMultiphaseWell/staircase_co2_wells_3d_01                       
FAIL RUN   : black_oil_wells_unsaturated_3d_04                 : compositionalMultiphaseWell/black_oil_wells_unsaturated_3d_04               
FAIL RUN   : black_oil_wells_unsaturated_3d_01                 : compositionalMultiphaseWell/black_oil_wells_unsaturated_3d_01                     
FAIL RUN   : black_oil_wells_saturated_3d_04                   : compositionalMultiphaseWell/black_oil_wells_saturated_3d_04                 
FAIL RUN   : black_oil_wells_saturated_3d_01                   : compositionalMultiphaseWell/black_oil_wells_saturated_3d_01                 
FAIL RUN   : PoroElastic_staircase_co2_3d_01                   : poroElasticCoupling/PoroElastic_staircase_co2_3d_01                         
FAIL RUN   : PoroElastic_staircase_co2_3d_04                   : poroElasticCoupling/PoroElastic_staircase_co2_3d_04                         
FAIL RUN   : deadOilEgg_smoke_3d_01                            : compositionalMultiphaseWell/deadOilEgg_smoke_3d_01                                
FAIL RUN   : staircase_co2_wells_hybrid_3d_08                  : compositionalMultiphaseWell/staircase_co2_wells_hybrid_3d_08

**Comment by rrsettgast** [comment]
@wrtobin The use of c++ exceptions has been against policy up to this point. This view may be outdated. Can you comment on the usage that exists now in the code after #2552 . 

Also, checks on values should be preprocessor guarded s.t. we can turn them off if desired.

**Comment by wrtobin** [comment]
Try-catch doesn't introduce substantial performance impact by being present, but it can impact runtime performance depending on how it is used.
It does create a lookup table to handle the exception throw / catch control flow mechanism, but that memory overhead should be insignificant barring quite deeply-nested callstacks and/or try-catch blocks. 

If we ever use it in a context where we try to recover from the error state, the performance impact is very significant, especially in the case it happens in a hot loop. If we want to recover from an error (especially in a kernel or other hot loop), we should prefer to set and check an error code, which has significantly less performance impact

So exceptions should only be used outside of kernels, and we should never attempt to recover from a thrown exception. When we catch, we should only print useful information before either (1) gracefully exiting the sim or (2) throwing an additional exception (which will eventually cause the sim to exit, gracefully or not).

It seems like #2552 only ever prints information and exits, which is exactly what we should limit our try-catch usage to.

**Comment by dkachuma** [comment]
@MelReyCG The check on the surface pressure and surface temperature on [CompositionalMultiphaseWell.cpp:663](https://github.com/GEOS-DEV/GEOS/blob/develop/src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp#L663) should apply only if `useSurfaceConditions` is true ([CompositionalMultiphaseWell.cpp:637](https://github.com/GEOS-DEV/GEOS/blob/develop/src/coreComponents/physicsSolvers/fluidFlow/wells/CompositionalMultiphaseWell.cpp#L637)).

I would also look to move this check away from the calculation method into something like `CompositionalMultiphaseWell::validateWellConstraints`.
