### ISSUE TITLE
MPI Run issue with MacOS, a few tests failed

### ISSUE THREAD

**Issue by zhx999** [GEOS-DEV/GEOS#2803]
When finish the configuration and try to run the geosx excutable,  message shows as follows:

Num ranks: 1
GEOSX version: 0.2.0 (develop, sha1: c7add4640)
  - c++ compiler: clang 15.0.0 ( apple version 15000040 )
  - MPI version: Open MPI v4.1.6, package: Open MPI brew@Ventura-arm64.local Distribution, ident: 4.1.6, repo rev: v4.1.6, Sep 30, 2023
  - HDF5 version: 1.12.1
  - Conduit version: 0.8.2
  - VTK version: 9.2.6
  - RAJA version: 2023.6.1
  - umpire version: 2023.6.0
  -  adiak version: ..
  - caliper version: 2.10.0
  - METIS version: 5.1.0
  - PARAMETIS version: 4.0.3
  - scotch version: 7.0.4
  - superlu_dist version: 6.3.0
  - suitesparse version: 5.7.9
  - Python3 version: 3.10.9
  - hypre release version: 2.29.0
USAGE: geosx -i input.xml [options]

Options:
-?, --help
-i, --input,             Input xml filename (required)
-r, --restart,           Target restart filename
-x, --x-partitions,      Number of partitions in the x-direction
-y, --y-partitions,      Number of partitions in the y-direction
-z, --z-partitions,      Number of partitions in the z-direction
-s, --schema,            Name of the output schema
-b, --use-nonblocking,   Use non-blocking MPI communication
-n, --name,              Name of the problem, used for output
-s, --suppress-pinned,   Suppress usage of pinned memory for MPI communication buffers
-o, --output,            Directory to put the output files
-t, --timers,            String specifying the type of timer output
--trace-data-migration,  Trace host-device data migration
-m, --memory-usage,      Minimum threshold for printing out memory allocations in a member of the data repository.
--pause-for,             Pause geosx for a given number of seconds before starting execution
libunwind: malformed __unwind_info at 0x191338EA4 bad second level page
Received signal 10: Bus error: 10

StackTrace of 0 frames 
Frame 0: _sigtramp 

MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.
NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

------------

When runing the tests, some of the tests failed. The messages are listed as follow:
The following tests FAILED:
	 52 - testInput (Bus error)
	 89 - testParsing (Bus error)
	 92 - testXmlWrapper (Bus error)
	106 - testMeshObjectPath (Bus error)
	126 - testXML (Failed)
	138 - testGroupPath (Failed)

Anyone has ideas to fix them? Thanks

**Comment by castelletto1** [comment]
We are sorry for the belated answer. We do not include MacOS among platforms for which we provide support.
