### ISSUE TITLE
Table input for CO2 solubility 

### ISSUE THREAD

**Issue by paveltomin** [GEOS-DEV/GEOS#2810]
Would be useful to have an option to provide CO2 solubility table directly instead of internal correlation

**Comment by paveltomin** [comment]
Once https://github.com/GEOS-DEV/GEOS/pull/2919 is merged, the way to provide external solubility table:
1) add
```
        <TableFunction
            name="BRINE_CO2Solubility_co2Dissolution_table"
            inputVarNames="{pressure, temperature}"
            coordinateFiles="{pres.txt, temp.txt}"
            voxelFile="sol.txt"
```
(`BRINE` is the name of the fluid)
2) create files: 
[sol.txt](https://github.com/GEOS-DEV/GEOS/files/13813910/sol.txt)
[temp.txt](https://github.com/GEOS-DEV/GEOS/files/13813911/temp.txt)
[pres.txt](https://github.com/GEOS-DEV/GEOS/files/13813912/pres.txt)

**Comment by dkachuma** [comment]
I would rather avoid the internally generated name in favour of a user specified name. Something like
```xml
<Functions>
  <TableFunction
    name="CO2_Solubility_Table"
    inputVarNames="{pressure, temperature}"
    coordinateFiles="{pres.txt, temp.txt}"
    voxelFile="sol.txt" />
</Functions>
<Constitutive>
  <CO2BrinePhillipsFluid
    name="BRINE"
    ...
    co2SolubilityTableName="CO2_Solubility_Table"
    phasePVTParaFiles="{ fluid/pvtgas.txt, fluid/pvtwat.Phillips.txt }" />
</Constitutive>
```
In such a case the user wouldn't have to specify the `flashModelParaFile` and there can be a more exact check that the specified table exists instead of the implied name.
