### ISSUE TITLE
PVT module broken on Pangea 3 - no reservoir simulation possible

### ISSUE THREAD

**Issue by sframba** [GEOS-DEV/GEOS#2823]
**Describe the bug**
Starting from [PR 2552](https://github.com/GEOS-DEV/GEOS/pull/2552), reservoir simulation is broken on Pangea3.
The `testPVT` unit test fails, and reservoir simulations fail at the beginning of the time loop.

**To Reproduce**
1. compile GEOS on Pangea 3
2. the `testPVT` unit test fails

**Comment by TotoGaz** [comment]
Hello @sframba this is really surprising. Can you share some logs?

**Comment by sframba** [comment]
@TotoGaz The original issue is probably fixed by #2812, by adding `GEOS_HOST_DEVICE` on conversion methods in `Units.hpp`. 
Unfortunately, another very similar issue appears after #2772 . But It seems to be tied to a direct access to private members of the class `PVTDriver` from device code. Hopefully it will be easy to fix
