### ISSUE TITLE
Replace integratedTests repository and remove submodule dependency

### ISSUE THREAD

**Issue by untereiner** [GEOS-DEV/GEOS#2824]
## Description
This is a proposal to remove chains between geos and the integrated tests.
Git is not a package manager. Submodules should not be used to handle version compatibility between packages.
It is really painful to merge develop into a branch and handling submodules (especially this one)
I don't understand the need. Is it practical for the people that are used to ?
Now (or soon) that the CI can launch them, there will be no more reason to keep this as submodule. 

## Work Scope
A discussion about what work will be done to achieve the goals of this `EPIC`.

hypothetical workflows:
1. Workflow geos
- Open a PR
- CI will launch the integrated tests (use the develop branch of the repo), depending on the result, PR can be merged or needs a rebaseline (workflow 2)

2. Workflow rebaseline
- Launch the scripts,
- Commit the things in develop branch
- Push to github
- back to workflow 1 - step launch integrated tests..

## Issues in this EPIC
none for now

**Comment by sframba** [comment]
I would like a lot if the rebaseline process were more streamlined. I like the idea of using flags in the PR to handle this.
As an external GEOS contributor, it would be great if we had a few CI scripts that do the following : 
* If the PR has the appropriate flag (e.g. `check integrated tests`) and has been reviewed
   + runs the integrated tests on an appropriate "reference" docker image
   + if there are differences, creates a branch with the same name as the GEOS branch, commits and push in the `integratedTests` repo. Also pushes a commit on the original repo updating the `integratedTests` module accordingly
This way, I can go check the results and verify which tests have to be rebaselined. Then, if I am OK with that:
* I add another flag to the PR (e.g. `automatic rebaseline`) to my PR, then 
   + the dependent PR on the integratedTests github repo is automatically created (maybe using something like the command `gh pr create` from the `hub` git extension https://hub.github.com/ ?)
   + Ideally the two PRs are linked together
The person in charge of the merge would then have all the info needed to merge the pull requests.

Am I daydreaming or would something like this be possible? @untereiner is this a good interpretation of what you would like to have?

**Comment by klevzoff** [comment]
> I don't understand the need. Is it practical for the people that are used to ?

Baselines are always generated by a particular version of the code. Having them detached from the code that is always evolving is meaningless - for which version of the code are these supposed to be "correct" solutions? For example, for someone working on a feature branch that was created off of `develop` a while ago, testing their local work against top of `develop` of `integratedTests` would produce a lot of false positives unrelated to their work. Yes, they will eventually need to update both their branch and baselines to test against, but while in the process this is an unnecessary distraction. In a large(-ish) distributed team, being able to precisely refer to multiple versions of test baselines seems essential to avoid confusion and hours wasted on manual change tracking.

On the technical side, ideally, we would just keep the baselines in the main repo, but this would make GEOS repo unnecessarily heavy to clone in certain contexts (e.g. in CI jobs that don't run tests). Submodules is the easiest way to maintain that version connection and also keep the main repo light. Granted, the workflow could be improved with more automation. Full automation is mainly constrained by available resources - we just don't have enough compute to run the full suite (including parallel jobs) on all PRs. We should aim to have each test complete within a few seconds and the whole suite in a matter of minutes, but historically that hasn't worked out.

**Comment by untereiner** [comment]
> interpretation of what you would like to have?

Yes, I would also that the CI checks if a rebase line is needed or not and adds the flag automatically.

> Baselines are always generated by a particular version of the code

What is needed is to store a particular hash from another repository into geos to refer to. This hash would evolve each time a rebaseline commit is made into the integrated test repo according to the geos repo. Am I wrong ?

It can be handle using git submodules as now. It could also be handled using CMake FetchContent. I think this second option would ease the maintenance of both repositories: compile geos in docker, share this image to next step in the pipeline that would fetch the integrated tests and run them.

> Having them detached from the code that is always evolving is meaningless

Yes but geos can live without. It is just how to keep a reference.

**Comment by rrsettgast** [comment]
@untereiner 
The issues with rebaselining are well known, well discussed, and multiple solutions are underway. If you would like to do some of the work, then please feel free to volunteer.

**Comment by untereiner** [comment]
@rrsettgast  And yet, for me, having them as a git submodule is a part of the issue. I would like to volunteer to transform them as a fetched content by cmake

**Comment by TotoGaz** [comment]
Hello @untereiner thanks for your proposition, there are lots of valuable items in it.

There're a lot of things happening in the CI for the moment and we're challenging what we're doing quite strongly.
We need to finish some task before some of your ideas can be implemented.

We won't be working on it right now, but we're keeping this issue in the backlog for the following steps.

Thank you for your initiative, we'll surely appreciate your help soon 🎉

**Comment by untereiner** [comment]
Hi @TotoGaz ! Great let me know when I can be of use

**Comment by TotoGaz** [comment]
@CusiniM I let you close this 😉
