### ISSUE TITLE
Does the stress mean the total stress or the effective stress in the THM models

### ISSUE THREAD

**Issue by FishYNY** [GEOS-DEV/GEOS#2830]
sorry to bother you. I'm confused that the stress means the total stress or the effective stress in the THM models.  Thanks a lot.

**Comment by sytuannguyen** [comment]
@FishYNY It is absolutely not the total stress. In case of PoroMechanical coupling (iso thermal) it is the effective stress. In THM case, it is the effective stress minus the thermal stress. Below is a post-processing script to compute the total stress from the output stress of GEOS.

![image](https://github.com/GEOS-DEV/GEOS/assets/45685596/8c95174d-b832-497f-8a40-64e70ac67b2a)


For more details, you may want to check the example https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/thermoPoroElasticWellbore/Example.html

**Comment by CusiniM** [comment]
I am closing this one since it seems resolved.
