### ISSUE TITLE
Error for FieldSpecification

### ISSUE THREAD

**Issue by 2020-cai** [GEOS-DEV/GEOS#2831]
When I export external .vtu file to simulation, one error is occurred as follow:
GEOSX version: 0.2.0 (develop, sha1: 23abbb8bf)
  - c++ compiler: gcc 8.4.0
  - MPI version: Open MPI v3.1.6, package: Open MPI root@gao Distribution, ident: 3.1.6, repo rev: v3.1.6, Mar 18, 2020
  - HDF5 version: 1.12.1
  - Conduit version: 0.8.2
  - VTK version: 9.2.6
  - RAJA version: 2023.6.1
  - umpire version: 2023.6.0
  -  adiak version: ..
  - caliper version: 2.10.0
  - METIS version: 5.1.0
  - PARAMETIS version: 4.0.3
  - scotch version: 7.0.3
  - superlu_dist version: 6.3.0
  - suitesparse version: 5.7.9
  - Python3 version: 3.8.10
  - hypre release version: 2.29.0
Started at 2023-11-21 03:57:30.532814332
Adding Mesh: VTKMesh, mesh1
Adding Event: SoloEvent, preFracture
Adding Event: PeriodicEvent, solverApplications
Adding Event: PeriodicEvent, outputs
Adding Event: PeriodicEvent, tractionHistoryCollection
Adding Event: PeriodicEvent, tractionHistoryOutput
Adding Event: PeriodicEvent, displacementHistoryCollection
Adding Event: PeriodicEvent, displacementHistoryOutput
Adding Solver of type LagrangianContact, named lagrangiancontact
Adding Solver of type SolidMechanics_LagrangianFEM, named lagsolve
Adding Solver of type SurfaceGenerator, named SurfaceGen
Adding Geometric Object: Rectangle, fracture1
Adding Geometric Object: Rectangle, core1
Adding Geometric Object: Rectangle, fracture2
Adding Geometric Object: Rectangle, core2
   TableFunction: ForceTimeFunction
   TableFunction: apertureTable
Adding Output: VTK, caicai
Adding Output: TimeHistory, tractionOutput
Adding Output: TimeHistory, displacementOutput
Adding Output: Restart, restartOutput
Adding Object CellElementRegion named Region from ObjectManager::Catalog.
Adding Object SurfaceElementRegion named Fracture from ObjectManager::Catalog.
VTKMesh 'mesh1': reading mesh from /home/weihanhuang/Geo/codes/Examples/Fracture_Interaction/Solid_Binary.vtu
Generating global Ids from VTK mesh
VTKMesh 'mesh1': generating GEOSX mesh data structure
Number of nodes:  3902
  Number of elems: 12458
             C3D4: 12458
Load balancing:   min   avg   max
(element/rank): 12458 12458 12458
No face block "faceElementSubRegion" was found in the mesh. Empty surface region was created.
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh1, Level0, Fracture, faceElementSubRegion
Adding aperture transition for table apertureTable:
    Original table = [ -0.001, 2e-06 ] [ 0, 2e-05 ]
    Modified table = [ -0.001, 2e-06 ] [ 0, 2e-05 ] [ 2.03666e-05, 2.03666e-05 ] [ 203666, 203666 ]
mesh1/Level0/Fracture/faceElementSubRegion/fractureMaterial allocated 8 quadrature points
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = mesh1, Level0, Region, 0_tetrahedra
mesh1/Level0/Region/0_tetrahedra/rock allocated 1 quadrature points
mesh1: importing field data from mesh dataset

***** LOCATION: /home/weihanhuang/Geo/codes/GEOSX/src/coreComponents/fieldSpecification/FieldSpecificationManager.cpp:179
***** Controlling expression (should be false): true
***** Rank 0:
xconstraint/objectPath (ContactMechanics_TFrac_base.xml, l.152): there is/are no set(s) named `xneg, xpos` under the objectPath `nodeManager`.

** StackTrace of 5 frames **
Frame 0: geos::FieldSpecificationManager::validateBoundaryConditions(geos::MeshLevel&) const
Frame 1: geos::ProblemManager::applyInitialConditions()
Frame 2: geos::GeosxState::applyInitialConditions()
Frame 3: main
Frame 4: __libc_start_main
Frame 5: _start
=====

**Comment by jeannepellerin** [comment]
Could you please share your simulation deck ? (XML file)

**Comment by 2020-cai** [comment]
My XML file and external mesh .vtu file present in attachment.




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "GEOS-DEV/GEOS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月21日(星期二) 晚上6:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GEOS-DEV/GEOS] Error for FieldSpecification (Issue #2831)





 
Could you please share your simulation deck ? (XML file)

**Comment by paveltomin** [comment]
don't see any attachment

**Comment by 2020-cai** [comment]
Please see the attachment 
[Uploading Test.zip…]()
