### ISSUE TITLE
Crash when SourceFlux targets non-simulated region

### ISSUE THREAD

**Issue by PBEYRIE** [GEOS-DEV/GEOS#2832]
Hello everyone, 

We were working on a water production grid with one producer box. 

This case was run with:
•	PANGEA-2 machine
•	gcc 8.3.0 compiler
•	the Geos version 99abae2

Geos crashed and I had this error: 

![image](https://github.com/GEOS-DEV/GEOS/assets/138772635/02aa5232-53f9-4fac-92b7-3764994e0555)

We figured out that we got this crash when a SourceFlux is applied on a Box that intersects with non-simulated region(s).

Here you'll find a minimal reproducing exemple: 

[SaltDome.zip](https://github.com/GEOS-DEV/GEOS/files/13428779/SaltDome.zip)

With the original case, we also encountered Floating Point Exceptions by adding extra region with fluid, but we didn't achieved to create a minimal reproducer yet.

**Comment by MelReyCG** [comment]
The Floating Point Exception comes from a division by 0 when computing average pressures of a region (in `RegionStatistics`) when porosities are not set (and therefore, equals to 0).
