### ISSUE TITLE
Unable to identify the model bounday (e.g., xneg, xpos) when external .vtu file is adopted

### ISSUE THREAD

**Issue by 2020-cai** [GEOS-DEV/GEOS#2848]
GEOSX version: 0.2.0 (develop, sha1: 23abbb8bf)
  - c++ compiler: gcc 8.4.0
  - MPI version: Open MPI v3.1.6, package: Open MPI root@gao Distribution, ident: 3.1.6, repo rev: v3.1.6, Mar 18, 2020
  - HDF5 version: 1.12.1
  - Conduit version: 0.8.2
  - VTK version: 9.2.6
  - RAJA version: 2023.6.1
  - umpire version: 2023.6.0
  -  adiak version: ..
  - caliper version: 2.10.0
  - METIS version: 5.1.0
  - PARAMETIS version: 4.0.3
  - scotch version: 7.0.3
  - superlu_dist version: 6.3.0
  - suitesparse version: 5.7.9
  - Python3 version: 3.8.10
  - hypre release version: 2.29.0
Started at 2023-11-26 03:13:02.078259946
Adding Solver of type SinglePhasePoromechanics, named thermoPoroSolver
Adding Solver of type SolidMechanicsLagrangianSSLE, named solidMechSolver
Adding Solver of type SinglePhaseFVM, named flowSolver
Adding Mesh: VTKMesh, CubeTetra
Adding Event: PeriodicEvent, outputs0
Adding Event: PeriodicEvent, outputs1
Adding Event: PeriodicEvent, outputs2
Adding Event: PeriodicEvent, outputs3
Adding Event: PeriodicEvent, outputs4
Adding Event: PeriodicEvent, pressureHistoryCollection0
Adding Event: PeriodicEvent, pressureTimeHistoryOutput0
Adding Event: PeriodicEvent, temperatureHistoryCollection0
Adding Event: PeriodicEvent, temperatureTimeHistoryOutput0
Adding Event: PeriodicEvent, displacementHistoryCollection0
Adding Event: PeriodicEvent, displacementTimeHistoryOutput0
Adding Event: PeriodicEvent, pressureHistoryCollection1
Adding Event: PeriodicEvent, pressureTimeHistoryOutput1
Adding Event: PeriodicEvent, temperatureHistoryCollection1
Adding Event: PeriodicEvent, temperatureTimeHistoryOutput1
Adding Event: PeriodicEvent, displacementHistoryCollection1
Adding Event: PeriodicEvent, displacementTimeHistoryOutput1
Adding Event: PeriodicEvent, pressureHistoryCollection2
Adding Event: PeriodicEvent, pressureTimeHistoryOutput2
Adding Event: PeriodicEvent, temperatureHistoryCollection2
Adding Event: PeriodicEvent, temperatureTimeHistoryOutput2
Adding Event: PeriodicEvent, displacementHistoryCollection2
Adding Event: PeriodicEvent, displacementTimeHistoryOutput2
Adding Event: PeriodicEvent, pressureHistoryCollection3
Adding Event: PeriodicEvent, pressureTimeHistoryOutput3
Adding Event: PeriodicEvent, temperatureHistoryCollection3
Adding Event: PeriodicEvent, temperatureTimeHistoryOutput3
Adding Event: PeriodicEvent, displacementHistoryCollection3
Adding Event: PeriodicEvent, displacementTimeHistoryOutput3
Adding Event: PeriodicEvent, pressureHistoryCollection4
Adding Event: PeriodicEvent, pressureTimeHistoryOutput4
Adding Event: PeriodicEvent, temperatureHistoryCollection4
Adding Event: PeriodicEvent, temperatureTimeHistoryOutput4
Adding Event: PeriodicEvent, displacementHistoryCollection4
Adding Event: PeriodicEvent, displacementTimeHistoryOutput4
Adding Event: PeriodicEvent, solverApplication0
Adding Event: PeriodicEvent, solverApplication1
Adding Event: PeriodicEvent, solverApplication2
Adding Event: PeriodicEvent, solverApplication3
Adding Event: PeriodicEvent, solverApplication4
   TableFunction: timeFunction
Adding Output: VTK, thermoPoroVTKOutput
Adding Output: TimeHistory, pressureHistoryOutput
Adding Output: TimeHistory, temperatureHistoryOutput
Adding Output: TimeHistory, displacementHistoryOutput
Adding Output: Restart, restartOutput
Adding Object CellElementRegion named Domain from ObjectManager::Catalog.
thermoPoroSolver: found SolverBase solver named flowSolver
thermoPoroSolver: found SolidMechanics_LagrangianFEM solver named solidMechSolver
VTKMesh 'CubeTetra': reading mesh from /home/weihanhuang/Geo/codes/Examples/MultipleFiled/Solid_Binary.vtu
Generating global Ids from VTK mesh
VTKMesh 'CubeTetra': generating GEOSX mesh data structure
Number of nodes: 2150
  Number of elems: 9864
             C3D4: 9864
Load balancing:  min  avg  max
(element/rank): 9864 9864 9864
regionQuadrature: meshBodyName, meshLevelName, regionName, subRegionName = CubeTetra, Level0, Domain, 0_tetrahedra
CubeTetra/Level0/Domain/0_tetrahedra/rock allocated 1 quadrature points
CubeTetra/Level0/Domain/0_tetrahedra/water allocated 1 quadrature points
CubeTetra/Level0/Domain/0_tetrahedra/thermalCond allocated 1 quadrature points
CubeTetra: importing field data from mesh dataset

***** LOCATION: /home/weihanhuang/Geo/codes/GEOSX/src/coreComponents/fieldSpecification/FieldSpecificationManager.cpp:179
***** Controlling expression (should be false): true
***** Rank 0:
xconstraint/objectPath (ThermoPoroElastic_consolidation_base.xml, l.133): there is/are no set(s) named `xneg, xpos` under the objectPath `nodeManager`.

** StackTrace of 5 frames **
Frame 0: geos::FieldSpecificationManager::validateBoundaryConditions(geos::MeshLevel&) const
Frame 1: geos::ProblemManager::applyInitialConditions()
Frame 2: geos::GeosxState::applyInitialConditions()
Frame 3: main
Frame 4: __libc_start_main
Frame 5: _start
=====

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.

**Comment by CusiniM** [comment]
This is not an error. Those node sets only make sense for a cuboid domain. With external meshes there is no guarantee that they actually have a meaning. You can create labels to tag the surfaces in the vtu files.
