### ISSUE TITLE
Host-device decorate conversion functions

### ISSUE THREAD

**Issue by wrtobin** [GEOS-DEV/GEOS#2860]
https://github.com/GEOS-DEV/GEOS/blob/69bee03d022992ba5c87bd9f61adeb512b6da449/src/coreComponents/common/Units.hpp#L36-L43

Need to be appropriately host-device decorated to avoid numerous warnings in GPU-enabled compilation.

**Comment by paveltomin** [comment]
https://github.com/GEOS-DEV/GEOS/pull/2812 ?
