### ISSUE TITLE
private field 'm_componentNames' is not used

### ISSUE THREAD

**Issue by cj215** [GEOS-DEV/GEOS#2880]
**Describe the bug**
Compilation error in file `GEOS/src/coreComponents/constitutive/fluid/multifluid/compositional/models/ComponentProperties.hpp:130:24` possibly caused by this commit https://github.com/GEOS-DEV/GEOS/pull/2799

```
In file included from /Users/clem/Documents/GitHub/GEOS/src/coreComponents/constitutive/fluid/multifluid/PVTDriver.cpp:24:
In file included from /Users/clem/Documents/GitHub/GEOS/src/coreComponents/constitutive/fluid/multifluid/MultiFluidSelector.hpp:30:
In file included from /Users/clem/Documents/GitHub/GEOS/src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluid.hpp:22:
In file included from /Users/clem/Documents/GitHub/GEOS/src/coreComponents/constitutive/fluid/multifluid/compositional/CompositionalMultiphaseFluidUpdates.hpp:22:
/Users/clem/Documents/GitHub/GEOS/src/coreComponents/constitutive/fluid/multifluid/compositional/models/ComponentProperties.hpp:130:24: error: private field 'm_componentNames' is not used [-Werror,-Wunused-private-field]
  string_array const & m_componentNames;
                       ^
1 error generated.
make[2]: *** [coreComponents/constitutive/CMakeFiles/constitutive.dir/fluid/multifluid/PVTDriver.cpp.o] Error 1
make[1]: *** [coreComponents/constitutive/CMakeFiles/constitutive.dir/all] Error 2
make: *** [all] Error 2]
```

**To Reproduce**
Building GEOS on macOS or Ubuntu 18.04 (where I had the error)

**Expected behavior**
Compilation fails

**Platform**
- Machine macOS or Ubuntu 18.04
- Compiler: Apple clang version 14.0.3
- GEOSX commit a1fd5613bc2040f9d96807c53d566795c7a3894e

**Comment by TotoGaz** [comment]
What is your compiler on `ubuntu`? Are you compiling in `Release` or `Debug` mode? (or both?)

**Comment by cj215** [comment]
On Ubuntu clang version 6.0.0-1ubuntu2 --> Quite old and can't be updated unless I update from 18.04 to 22.04 hence I went on macOS to avoid doing that

I am compiling in Release mode, I have not tried Debug

**Comment by TotoGaz** [comment]
Is the `warning` is legitimate?

**Comment by cj215** [comment]
Thanks, this has removed the error and promted another one. The error is quite similar on both macOS and Ubuntu, I am going to be looking into this in the next few days
[macOs error.txt](https://github.com/GEOS-DEV/GEOS/files/13640030/macOs.error.txt)
[Ubuntu 18_04 error.txt](https://github.com/GEOS-DEV/GEOS/files/13640036/Ubuntu.18_04.error.txt)
