### ISSUE TITLE
Well output rates folder located in run directory not the output directory

### ISSUE THREAD

**Issue by cssherman** [GEOS-DEV/GEOS#2882]
**Describe the bug**
Running the integrated tests, a bunch of folders with well rates are left over when the ATS veryclean method is called.  I assume this is because they are not output to the usual results folder specified by the command line `-o` option.

**Comment by paveltomin** [comment]
sorry about that and thanks for reporting and pointing in the right direction
just submitted the fix here https://github.com/GEOS-DEV/GEOS/pull/2884
