### ISSUE TITLE
Something wrong when restart (conduit_node) 

### ISSUE THREAD

**Issue by Ron-Wang** [GEOS-DEV/GEOS#2898]
**Describe the bug**
There is something wrong when I run GEOSX using a resrart file. It says
"
{
  "file": "/es01/paratera/sce0181/GEOSX22/thirdPartyLibs/build-Ubuntu18-release/conduit/src/conduit/src/libs/conduit/conduit_node.cpp",
  "line": 13181,
  "message": "Node::as_signed_int() const -- DataType empty at path Problem/domain/MeshBodies/ML/Level0/nodeManager/neighborData/46/matchedPartitionBoundaryObjects/__sizedFromParent__ does not equal expected DataType int32"
}

application called MPI_Abort(MPI_COMM_WORLD, 1) - process 49
"
I think it may be something wrong about the restart file using parallelization. 

**Platform (please complete the following information):**
- Machine [Ubuntu18] 
- Compiler: [gcc 8.3.0]
- GEOSX Version [0.2.0]

**Comment by klevzoff** [comment]
@Ron-Wang what is the specific GEOS commit you are running (it should first thing in your output)? A bug was fixed a few months ago that could have caused this.

**Comment by Ron-Wang** [comment]
Thanks for your reply. 
The GEOSX commit I am running is "mpirun -np 89 ../GEOSX23/GEOSX/build-Ubuntu18-release/bin/geosx -i include_input.xml -r include_input_restart_001899997".

**Comment by Ron-Wang** [comment]
> @Ron-Wang what is the specific GEOS commit you are running (it should first thing in your output)? A bug was fixed a few months ago that could have caused this.

I think there is something wrong when restart.

**Comment by klevzoff** [comment]
I mean version of the code, you can see it at the top of command line output, e.g.
```
GEOS version: 0.2.0 (develop, sha1: 95ddd594)
```
I'm interested in what is printed for you instead of `95ddd594`

**Comment by Ron-Wang** [comment]
> I mean version of the code, you can see it at the top of command line output, e.g.
> 
> ```
> GEOS version: 0.2.0 (develop, sha1: 95ddd594)
> ```
> 
> I'm interested in what is printed for you instead of `95ddd594`

I feel so sorry that i have misunderstood your words. It is an old version in which i have developed some solvers in 2022. I can not see the version of the code, as the top of command line output is just "GEOSX version 0.2.0".
I believe that the bug you mentioned is still in this version.

**Comment by klevzoff** [comment]
> > I mean version of the code, you can see it at the top of command line output, e.g.
> > ```
> > GEOS version: 0.2.0 (develop, sha1: 95ddd594)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm interested in what is printed for you instead of `95ddd594`
> 
> I feel so sorry that i have misunderstood your words. It is an old version in which i have developed some solvers in 2022. I can not see the version of the code, as the top of command line output is just "GEOSX version 0.2.0". I believe that the bug you mentioned is still in this version.

No problem! I see now, you are probably building from a source tree that is not a git repository, so you don't get extended version output.

I would suggest that you update your code to the latest GEOS version, if possible. If that is not feasible for you, try applying this change manually to your code (luckily, it's very small): https://github.com/GEOS-DEV/GEOS/pull/2608/files

Let us know if this fixes the issue.

**Comment by Ron-Wang** [comment]
Yep, klevzoff !
I feel so pity that it is difficult to update my code to the last GEOS version (We will do it in the future). I apply the change as your suggestion and  it works! I am so gateful for your help!
