### ISSUE TITLE
Some `integratedTests` are skipped because of the n° of processes

### ISSUE THREAD

**Issue by tbeltzun** [GEOS-DEV/GEOS#2900]
**Describe the bug**

Some `integratedTests` are skipped because of the n° of requested processes.
See e.g. https://github.com/GEOS-DEV/GEOS/actions/runs/7260930520/job/19781362917?pr=2813#step:6:2597.

**Expected behavior**

All integratedTests are ran.

**Comment by TotoGaz** [comment]
Relates to https://github.com/GEOS-DEV/GEOS/issues/2800

**Comment by paveltomin** [comment]
should be fixed after https://github.com/GEOS-DEV/GEOS/pull/2991
