### ISSUE TITLE
Negative pressure with Box / SourceFlux

### ISSUE THREAD

**Issue by MelReyCG** [GEOS-DEV/GEOS#2912]
**Describe the bug**
Negative pressure involved by a `Box` / `SourceFlux`.

--------------------

**To Reproduce**
Minimal reproducing case:

1. Working exemple (see comments in `singlePhaseFlowTest_sinkBox1.xml`)
[sinkBox1.zip](https://github.com/GEOS-DEV/GEOS/files/13754062/sinkBox1.zip)

Conditions at simulation end:
```
Time: 1.99e+09 s, dt: 3155760 s, Cycle: 632
compflowStatistics, Reservoir: Pressure (min, average, max): 5.9415e+06, 9.79579e+06, 1.42887e+07 Pa
compflowStatistics, Reservoir: Delta pressure (min, max): -4.0573e+06, 4.28837e+06 Pa
compflowStatistics, Reservoir: Temperature (min, average, max): 0, 0, 0 K
compflowStatistics, Reservoir: Total dynamic pore volume: 1.36469e+09 rm^3
compflowStatistics, Reservoir: Total fluid mass: 1.37807e+12 kg
```

2. Exemple with negative pressures (see comments in `singlePhaseFlowTest_sinkBox2.xml`)
[sinkBox2.zip](https://github.com/GEOS-DEV/GEOS/files/13754065/sinkBox2.zip)

Conditions at simulation end:
```
Time: 1.99e+09 s, dt: 3155760 s, Cycle: 632
compflowStatistics, Reservoir: Pressure (min, average, max): -1.40178e+08, -1.05213e+07, 1.14307e+07 Pa
compflowStatistics, Reservoir: Delta pressure (min, max): -1.50456e+08, 1.43144e+06 Pa
compflowStatistics, Reservoir: Temperature (min, average, max): 0, 0, 0 K
compflowStatistics, Reservoir: Total dynamic pore volume: 1.33422e+09 rm^3
compflowStatistics, Reservoir: Total fluid mass: 1.32056e+12 kg
```

(fluid mass obtained thanks to PR #2904 )

--------------------

**Expected behavior**
Negative pressures should not appear.

**Comment by paveltomin** [comment]
Negative pressure is allowed by default for single phase https://geosx-geosx.readthedocs-hosted.com/en/latest/coreComponents/schema/docs/SinglePhaseFVM.html#
The main reason is that there are some integration tests that fall into negative pressure values, physically it should not happen for non-hydrofrac simulations but still in your case I am afraid if you try to set `allowNegativePressure="0"` the second simulation will just fail to finish. If production is big and not compensated by injection, pressure will go down and nothing really prevents it not to go negative.

**Comment by jeannepellerin** [comment]
Our objective with this case is to reproduce issues on a real case where pressures largely below - 1000 bars appear when trying to reproduce production profiles using boxes

**Comment by paveltomin** [comment]
did you try to estimate the pressure change using basic material balance relations?
with linear compressibility (and small) and sufficiently large production, pressure will go negative
are you proposing to change compressibility model or something else?
