### ISSUE TITLE
Volumetric Heat Capacity Values are Off for THM Examples

### ISSUE THREAD

**Issue by cssherman** [GEOS-DEV/GEOS#2923]
In some of the thermoporomechanics examples, the specified volumetric heat capacities look incorrect (for example, see: https://github.com/GEOS-DEV/GEOS/blob/develop/inputFiles/thermoPoromechanics/ThermoPoroElastic_consolidation_base.xml#L49-L68 ).

In these, the rock phase has a value equal to 1.672e5, and the fluid has a value of 1.672e2.  Looking at some online references, reasonable values for rock are about 3e6, and for water is about 4e6.  This is obviously off from the reality.   Looking at the formulation we use for the THM model with @frankfeifan , we suspect that the existing models are effectively ignoring everything aside from conduction. 

In addition, I've found that when these values are fixed, that the solvers can struggle to converge, and report very large residuals for Renergy.

To address this issue, we should do the following:

1) Use appropriate values for the volumetric heat capacity (or at least ones withe the correct ratio between solid/fluid)
2) Run the examples, and address any scaling problems that arise (we may need to address the MGR recipe)

**Comment by frankfeifan** [comment]
I have reviewed the code and found the heat capacity we use for the fluid is defined on the **unit mass** instead of **unit volume**. So the current naming of fluid heat capacity is incorrect and misleading. We should fix it as soon as possible. 

That said, the values in this example may be reasonable.
