### ISSUE TITLE
VTU cells configuration in case xml file

### ISSUE THREAD

**Issue by assabharwal** [GEOS-DEV/GEOS#2925]
Trying to create a run case for Sleipner dataset using vtp and vtu files converted using PyGRDECL, how would you setup a case file to run? I have the VTP and VTU files, i want to setup the coordinates and case run

**Comment by paveltomin** [comment]
https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/tutorials/step02/Tutorial.html
