### ISSUE TITLE
Feedback on Tutorial 3 - Initial pressure is set constant and not at equilibrium

### ISSUE THREAD

**Issue by jeannepellerin** [GEOS-DEV/GEOS#2939]
Setting the Initial pressure at 1e7 in the model of tutorial 3 where Z variations are large (at least 1000m) results in instabilities.
![image](https://github.com/GEOS-DEV/GEOS/assets/48675268/3a3566bf-8624-4b7b-a2d6-402815f79b01)

Using an HydrostaticEquilibrium with 1e7 Pa at -793 fixes the issue.
![image](https://github.com/GEOS-DEV/GEOS/assets/48675268/1f75fddb-7590-45bc-967b-ce9798761670)

Purpose of Tutorial 3 is not to validate final results, question therefore is what should be modified ?
Maybe the geometry of the model to flatten it.

**Comment by paveltomin** [comment]
> Setting the Initial pressure at 1e7 in the model of tutorial 3 where Z variations are large (at least 1000m) results in instabilities. ![image](https://private-user-images.githubusercontent.com/48675268/297447716-3a3566bf-8624-4b7b-a2d6-402815f79b01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MTAxMTUsIm5iZiI6MTcwNTUwOTgxNSwicGF0aCI6Ii80ODY3NTI2OC8yOTc0NDc3MTYtM2EzNTY2YmYtODYyNC00YjdiLWEyZDYtNDAyODE1Zjc5YjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDE2NDMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5Zjg2NTcwOWU0MjMwM2EyYWVlNTBjNzFkYzNmYjYyNzYxYjIyZTExMWFhZjM1ZGNkODRlM2NiYzNmMDE2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jOPx3rJRf79FIabQiZeMCXrmUbpX9J-vWyOqVeCrwAE)

This looks like numerical noise (values are close but not equal), not really an instability
