### ISSUE TITLE
Handle input data from a complex source

### ISSUE THREAD

**Issue by untereiner** [GEOS-DEV/GEOS#2953]
**Describe the issue**
For now, one input mesh is read from from one vtu file.
Their are also surfaces embedded in this vtu file using the potpourri ability of this file format.

I am considering more complex files format where data is (or can be) organized semantically. 
There is of course RESQML but we can also consider VTK composite meshes such as [vtkPartitionedDataSetCollection](https://vtk.org/doc/nightly/html/classvtkPartitionedDataSetCollection.html)

It is not fairly possible to add a new node in `Problem`. It would require a new manager and to find a place in the order of the managers.

**Proposed cleanup**
I suggest for now to add a new abstract level above `MeshGeneratorBase` that would allow a new subtree of classes to handle such cases
I am already using it with the branch feature/untereiner/wip. I will propose a cleaned version

**Additional context**

**Comment by TotoGaz** [comment]
I do not understand what mesh feature is missing ?
BTW, fractures are defined in their own separate `vtu` file, all the `vtu` files being combined into a `vtm` file. The same is meant to be done for embedded surfaces.

**Comment by untereiner** [comment]
I should have missed something because on my side I have a vtu file with an UnstructuredGrid and surfaces inside.
No feature is missing for using meshes stored in vtu files. The refactor allows to use other formats where the API of `MeshGenerationBase` doesn't fit
