### ISSUE TITLE
Restart for Lagrange multiplier contact solver

### ISSUE THREAD

**Issue by castelletto1** [GEOS-DEV/GEOS#2979]
No Lagrange multiplier contact solver smoke test is checking the restart option. Currently only the [ContactMechanics_SimpleCubes](https://github.com/GEOS-DEV/integratedTests/blob/87d50ac32f892accd235af801928a63d99f77d1f/tests/allTests/contactMechanics/contactMechanics.ats#L10-L15) test should check it. My understanding is that, because of the unclear numbering logic discussed in [issue #7](https://github.com/GEOS-DEV/geosPythonPackages/issues/7) in  the geos python packages, no actual restart is happening. The attempt of checking the restart option for the two new smoke tests introduced in PR #2970 (`ContactMechanics_slippingFault_horizontal`, `ContactMechanics_slippingFault_vertical`), with `restart_step=5`, resulted in persistent `fail check` since the fracture status, in this case `slip`, is always initialized to `stick` at restart, hence triggering a different number of successful nonlinear iterations (12 vs 11), linear iteration (12 vs 11), and outer loop iterations (2 vs 1).

**Comment by CusiniM** [comment]
https://github.com/GEOS-DEV/GEOS/pull/3302 and https://github.com/GEOS-DEV/GEOS/pull/3322 should have fixed this.
