### ISSUE TITLE
Four Identical CO2 Injection Wells not Behaving Identically

### ISSUE THREAD

**Issue by CharlesHostetler** [GEOS-DEV/GEOS#2980]
We are trying to run a very simple CO2 injection problem with GEOS.  There are three horizontal layers; the middle one is configured as an injection interval (high permeability).  The upper and lower layers are configured as seals (low permeability).  We have four injection wells with perforations in the injection zone.  The four wells have (what we believe are) identical constructions (in the vertical sense), identical perforations, and identical well controls and schedules.  

When we run the model, the four wells are not behaving identically.  Two of them (OIW-1 and OIW-3) cycle back and forth between volume control and BHP constraint.  These wells also inject much less CO2 that the others.  They also have pressure buildups that are about a factor of 3 smaller that the other two.  The initial conditions (we think) are all the same throughout the injection zone (set hydrostatic).  

![deltaP](https://github.com/GEOS-DEV/GEOS/assets/126977849/8e3650f2-1747-47f0-b80a-a42bc4e3f85b)
![PhaseComp](https://github.com/GEOS-DEV/GEOS/assets/126977849/0dcbb603-0232-48bf-a08c-544a96bb6a40)
<img width="2560" alt="RunLog" src="https://github.com/GEOS-DEV/GEOS/assets/126977849/cdb35d5a-d94d-4e4d-ad10-ba476c5d0129">

We also tried turning all of the wells off but one, and move the active well around (in x and y).  The injection amount and pressure buildup varies with location.  

The input files for the 4 well problem are attached.  We are clearly missing something very basic - this model was built from several of the tutorials and perhaps there's some switch set that we copied inappropriately.  Otherwise we are baffled and would appreciate any help.  Thanks!

[Input Files.zip](https://github.com/GEOS-DEV/GEOS/files/14213705/Input.Files.zip)

**Comment by jhuang2601** [comment]
@CharlesHostetler I tried to reproduce your issue; however, the case cannot be running with current develop repository.
Some warnings were given for your current well/perforation settings:
```
The GEOSX wells currently have the following limitation in parallel: 
We cannot allow an element of the well mesh to have two or more perforations associated with it. 
So, in the present simulation, perforation #1 of well NIW1 is moved from { 0, 0, -1910 } to { 0, 0, -1880 } to make sure that no element of the well mesh has two perforations associated with it. 
To circumvent this issue, please increase the value of "numElementsPerSegment" that controls the number of (uniformly distributed) well mesh elements per segment of the well polyline. 
Our recommendation is to choose "numElementsPerSegment" such that each well mesh element has at most one perforation. 



 
The GEOSX wells currently have the following limitation in parallel: 
We cannot allow an element of the well mesh to have two or more perforations associated with it. 
So, in the present simulation, perforation #2 of well NIW1 is moved from { 0, 0, -1940 } to { 0, 0, -1880 } to make sure that no element of the well mesh has two perforations associated with it. 
To circumvent this issue, please increase the value of "numElementsPerSegment" that controls the number of (uniformly distributed) well mesh elements per segment of the well polyline. 
Our recommendation is to choose "numElementsPerSegment" such that each well mesh element has at most one perforation. 
```
And similar warnings for other wells and perforations.
Here is the meaningful error message for how to improve the case. 
```
***** LOCATION: /work206/workrd/SCR/GEOSX/j0551570/dev/GEOS_P2_Compilation/Build_020724/GEOS/src/coreComponents/mesh/WellElementRegion.cpp:79
***** Controlling expression (should be false): matchedPerforations != numPerforationsGlobal
***** Rank 12: Invalid mapping perforation-to-element in InternalWell NIW1. This happens when GEOSX cannot match a perforation with a reservoir element. There are two common reasons for this error:
 1- The most common reason for this error is that a perforation is on a section of  the well polyline located outside the domain.
 2- This error can also happen if a perforation falls on a mesh face or a mesh vertex. Please try to move the perforation slightly (to the interior of the perforated cell) to see if it fixes the problem.
```
I would suggest to update your compilation with most recent develop repo and modify your well/perforation settings accordingly.

**Comment by CharlesHostetler** [comment]
Thank you for your help!  I will update the compilation as soon as I can.  In the interim, we made a run to test this idea out:

1. moved each well so that it is in the center of it's reservoir grid block.
2. changed  numElementsPerSegment="4" so each well segment only has 1 perforation
3. moved the perforations vertically such that each one is in the center of a well segment and none are on reservoir cell faces or vertices.  

It ran fine but we got the same result.  Two of the wells are behaving differently than the other two.  

![DeltaP_update](https://github.com/GEOS-DEV/GEOS/assets/126977849/cada9b91-fe5c-4988-906f-0b6e6e21ae17)

The updated mesh file is:

<?xml version="1.0" ?>

<Problem>

    <Mesh>
     <InternalMesh
        name="cartesianMesh"
        elementTypes="{ C3D8 }"
        xCoords="{ -32000.0, 32000.0 }"
        yCoords="{ -32000.0, 32000.0 }"
        zCoords="{ -2000.0, -1980.0, -1850.0, -1800.0 }"
        nx="{ 100 }"
        ny="{ 100 }"
        nz="{ 10, 65, 25 }"
        cellBlockNames="{ cb1, cb2, cb3 }">

        <InternalWell
          name="NIW1"
          wellRegionName="wellRegion_NIW1"
          wellControlsName="wellControls_NIW1"
          logLevel="0"
          polylineNodeCoords="{ { -320.0, 320.0, -1850.00 },
                                { -320.0, 320.0, -1980.00 } }"
          polylineSegmentConn="{ { 0, 1 } }"
          radius="0.1"
          **numElementsPerSegment="4" >
          <Perforation name="NIW1-P01" distanceFromHead="16.25"/>
          <Perforation name="NIW1-P02" distanceFromHead="48.75"/>
          <Perforation name="NIW1-P03" distanceFromHead="81.25"/>
          <Perforation name="NIW1-P04" distanceFromHead="113.75"/>
        </InternalWell>**
        
        <InternalWell
          name="OIW1"
          wellRegionName="wellRegion_OIW1"
          wellControlsName="wellControls_OIW1"
          logLevel="0"
          polylineNodeCoords="{ { -16960.0, 16960.0, -1850.00 },
                                { -16960.0, 16960.0, -1980.00 } }"
          polylineSegmentConn="{ { 0, 1 } }"
          radius="0.1"
          numElementsPerSegment="4" >
          <Perforation name="OIW1-P01" distanceFromHead="16.25"/>
          <Perforation name="OIW1-P02" distanceFromHead="48.75"/>
          <Perforation name="OIW1-P03" distanceFromHead="81.25"/>
          <Perforation name="OIW1-P04" distanceFromHead="113.75"/>
        </InternalWell>
        
        <InternalWell
          name="OIW2"
          wellRegionName="wellRegion_OIW2"
          wellControlsName="wellControls_OIW2"
          logLevel="0"
          polylineNodeCoords="{ { 11200.0, 11200.0, -1850.00 },
                                { 11200.0, 11200.0, -1980.00 } }"
          polylineSegmentConn="{ { 0, 1 } }"
          radius="0.1"
          **numElementsPerSegment="4" >
          <Perforation name="OIW2-P01" distanceFromHead="16.25"/>
          <Perforation name="OIW2-P02" distanceFromHead="48.75"/>
          <Perforation name="OIW2-P03" distanceFromHead="81.25"/>
          <Perforation name="OIW2-P04" distanceFromHead="113.75"/>
        </InternalWell>**
        
        <InternalWell
          name="OIW3"
          wellRegionName="wellRegion_OIW3"
          wellControlsName="wellControls_OIW3"
          logLevel="0"
          polylineNodeCoords="{ { -320.0, -8000.0, -1850.00 },
                                { -320.0, -8000.0, -1980.00 } }"
          polylineSegmentConn="{ { 0, 1 } }"
          radius="0.1"
          numElementsPerSegment="4" >
          <Perforation name="OIW3-P01" distanceFromHead="16.25"/>
          <Perforation name="OIW3-P02" distanceFromHead="48.75"/>
          <Perforation name="OIW3-P03" distanceFromHead="81.25"/>
          <Perforation name="OIW3-P04" distanceFromHead="113.75"/>
        </InternalWell>
        
     </InternalMesh>
    </Mesh>
  
</Problem>

All of the wells are constructed and perforated identically.  If there was a flaw with the specifications of one of them they should have all failed, yet two of them are different from the other two?

**Comment by tjb-ltk** [comment]
I ran the case for a few timesteps and NIW1 matches OIW2,  OIW1 and OIW3 are similar but still different.
A good test would be to place the wells so that each is same distance from a corner.    Assuming the grid props support this symmetry it should eliminate different profiles due to distance between injectors..   If they are the same then I would look at cross sections of the original model to study the fronts... otherwise post the model

**Comment by paveltomin** [comment]
maybe try after this fix https://github.com/GEOS-DEV/GEOS/pull/3034
if still does not work as expected - reopen the issue
