### ISSUE TITLE
Unclear Error Message (Floating Point Exception)

### ISSUE THREAD

**Issue by Oluwatobi-PM** [GEOS-DEV/GEOS#3069]
I get an error message that says floating point exception when I run my simulation but it is not clear what exactly is generating this error so I can fix it in the model. I have attached a copy of my log file to this issue so you can see it. 

[output_geos.txt](https://github.com/GEOS-DEV/GEOS/files/14899549/output_geos.txt)

**Comment by paveltomin** [comment]
can you share xml input?

**Comment by jafranc** [comment]
Hi @Oluwatobi-PM,

- Can you confirm you are working on Sherlock from SMARTFIELD group ?
- Can you try with what @matteofrigo5 deployed there ? Can you try having it compiled in `Debug` ?
- Can you share a small reproducer as @paveltomin asked ? Is there a test in `inputFiles` that already raise the same type error on your end ?

**Comment by paveltomin** [comment]
can not be fixed without input
