### ISSUE TITLE
Building geos faillure

### ISSUE THREAD

**Issue by Yacineterbou** [GEOS-DEV/GEOS#3143]
i experiencing warnings and errors during the compilation process. The warnings indicate partially overridden virtual functions in the classes WellSolverBase and FlowSolverBase, which inherit from the base class SolverBase. These warnings suggest potential inconsistencies in function signatures or implementations between the base and derived classes. Additionally, the compilation process fails with an error while building CompositionalMultiphaseBase.cpp, resulting in an Error 137. This error halts the compilation, and there are also unfinished jobs, indicating possible interference from previous processes.

**Comment by CusiniM** [comment]
Can you provide a log and some details about the system you are using?
