### ISSUE TITLE
Does GEOS support inject source on embedded fractures when considering THM coupling issues?

### ISSUE THREAD

**Issue by tina3123** [GEOS-DEV/GEOS#3144]
Dear all,

I always encounter a non-convergence problem when implementing a source injector while using the THM coupling solver _SinglePhasePoromechanicsEmbeddedFractures_. I'm not sure if the current version of GEOS supports injection source box on the fracture region or if there are specific parameter settings related to _NonlinearSolverParameters_ / _LinearSolverParameters_ elements that I should consider (e.g., _solverType, preconditionerType_, although I have tried with different combinations).
I hope to hear your advice. Thanks for your efforts!

Best,
Ting

**Comment by CusiniM** [comment]
> Dear all,
> 
> I always encounter a non-convergence problem when implementing a source injector while using the THM coupling solver _SinglePhasePoromechanicsEmbeddedFractures_. I'm not sure if the current version of GEOS supports injection source box on the fracture region or if there are specific parameter settings related to _NonlinearSolverParameters_ / _LinearSolverParameters_ elements that I should consider (e.g., _solverType, preconditionerType_, although I have tried with different combinations). I hope to hear your advice. Thanks for your efforts!
> 
> Best, Ting

Hi, can you provide an xm?  If you are not using a well, the feature should be supported.
