### ISSUE TITLE
Thermal debonding validation example is not valid

### ISSUE THREAD

**Issue by sytuannguyen** [GEOS-DEV/GEOS#3169]
I have re-run the thermal debonding example with the link given below. It is no more valid with the present GEOS version. Some recent modifications have made this example invalid.

Link to the example: 

https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/advancedExamples/validationStudies/wellboreProblems/casedContactThermoElasticWellbore/Example.html

Invalid results observed from my recent re-run, we expect to obtain a perfect fit between GEOS and reference results as shown in the link above. However, my recent re-run give an invalid comparion as shown in the figure below:

![image](https://github.com/GEOS-DEV/GEOS/assets/45685596/ad5fbbf8-10c4-4eb3-95c5-df99ce8ca89c)

When I plot the casing-cement and cement-rock interfaces, it plots something strange as shown in the figure below. The good visualization can be found in the link above.

![image](https://github.com/GEOS-DEV/GEOS/assets/45685596/04b331ca-4791-498e-bde5-18041a46456d)

**Comment by jhuang2601** [comment]
Hello @sytuannguyen, there are two different issues related to this tutorial example:

-  Inconsistency in the ordering of node list between surface generated fracture and imported ones
   If running the case with (#3133), expected visualization of interfaces is shown below:
![image](https://github.com/GEOS-DEV/GEOS/assets/53012159/f3c81827-db91-4c69-ae69-1582ad977196)

-  Update of parallel plate permeability model (#2623)
   If using ` defaultAperture="5.0e-4"`, following match between reference solution and GEOS result can be obtained:
![image](https://github.com/GEOS-DEV/GEOS/assets/53012159/2d1da731-66f8-47de-a0ba-2ed1bb338d51)

**Comment by sytuannguyen** [comment]
Perfect fix, thank Jian!
