### ISSUE TITLE
error: ‘void* __builtin_memmove(void*, const void*, long unsigned int)’ forming offset 4 is out of the bounds

### ISSUE THREAD

**Issue by Neo-Zhu** [GEOS-DEV/GEOS#3182]
Excuse me, when i build geos using the codes: make -j4, there is the error:
       error: ‘void* __builtin_memmove(void*, const void*, long unsigned int)’ forming offset 4 is out of the bounds [0, 4] [-Werror=array-bounds=]
           __builtin_memmove(__result, __first, sizeof(_Tp) * _Num);

i don't know how to solve it.  i appricaite it so much if you give me some suggestions. Thanks in advanced!

**Comment by victorapm** [comment]
@Neo-Zhu can you provide more details about this error?

1. Machine type
2. Compiler used
3. GEOS version
4. Full error message (a few lines above the message you shared)

This information will help us diagnose the problem more effectively. Thank you!

**Comment by Neo-Zhu** [comment]
Thank you. I have solved the problem by changing my gcc-13 to gcc-8 that you recommended in GEOSX docoment.
