### ISSUE TITLE
Pre-split tags can be erroneous 

### ISSUE THREAD

**Issue by sohailwaziri** [GEOS-DEV/GEOS#3222]
If a mesh file has tags and the mesh is split using mesh_doctor, the pre-split tags might no longer be valid. To avoid unexpected behavior, please tag your boundaries/edges/etc explicitly in your xml input file using Geometry element.

**Comment by ryar9534** [comment]
Might want to also mention this directly in geos python packages repo

Also @alexbenedicto this might also be something to look at

**Comment by alexbenedicto** [comment]
I agree with @ryar9534 

Would it be possible @sohailwaziri for you to create an issue in :
https://github.com/GEOS-DEV/geosPythonPackages/issues

Also, if you could provide an example of erroneous behavior in that issue would be great.

**Comment by ryar9534** [comment]
For reference @paveltomin, Alex just started on the TotalEnergies side here in California, and he is going to be focussing on mesh_doctor. Not sure how much context you already had :)

**Comment by paveltomin** [comment]
@alexbenedicto feel free to assign yourself to that issue and thanks for your help

**Comment by sohailwaziri** [comment]
@alexbenedicto issue created in https://github.com/GEOS-DEV/geosPythonPackages/issues

**Comment by paveltomin** [comment]
closing since https://github.com/GEOS-DEV/geosPythonPackages/issues/31 is closed
