### ISSUE TITLE
Is there any runtime test for GEOS?

### ISSUE THREAD

**Issue by miraboreasumr** [GEOS-DEV/GEOS#3226]
Not sure if this belongs to issues, but there is definitely need of runtime tests

**Comment by rrsettgast** [comment]
Hello @miraboreasumr. There are a multitude of runtime tests as part of the `integratedTests` suite. I am not sure if you mean something else?

**Comment by CusiniM** [comment]
@miraboreasumr, did @rrsettgast answer your question? Can I close this issue?
