### ISSUE TITLE
Improved handling of NaNs

### ISSUE THREAD

**Issue by victorapm** [GEOS-DEV/GEOS#3281]
**What is the requested feature?**

Warning message when NaNs are found in GEOS, removing the ambiguity over the source of the issue (linear solver or GEOS)

**Is your request related to a specific problem?**

The following leads to a crash in hypre, but the problem is on the linear system assembled in GEOS.
```
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  0
        ( Rflow ) = ( 2.18e-01 )        ( Rsolid ) = ( -nan )        ( R ) = ( -nan )
```

**Describe the solution you'd like**

A warning message like:
```
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  0
        ( Rflow ) = ( 2.18e-01 )        ( Rsolid ) = ( -nan )        ( R ) = ( -nan )

*********************************************************************
*                    WARNING! WARNING! WARNING!                     *
*                                                                   *
*  The assembled sparse linear system contains invalid numbers      *
*  (NaNs). This may cause the solver to fail. Please check your     *
*  input values, boundary conditions, or model setup for potential  *
*  issues that might lead to these errors.                          *
*********************************************************************

```

**Comment by rrsettgast** [comment]
There should be a floating point exception that is thrown upon the generation of a nan. Someone must have disabled this...unless this is on a Mac. I don't think we throw fpe exceptions on macOS
