### ISSUE TITLE
Unable to run Geos on Pangea 3 with shared libraries

### ISSUE THREAD

**Issue by acitrain** [GEOS-DEV/GEOS#3305]
**Describe the bug**
Since the merge of PR #3282 we are unable to run GEOS on Pangea3 due to issue on a powerpc architecture to run with shared libraries. We get the follopwing error at the execution: 

geos: error while loading shared libraries: libmainInterface.so: cannot open shared object file: No such file or directory

And sometimes we are unable to compile (error at the link edition) 

**Platform (please complete the following information):**
- Machine Pangea 3
- Compiler gcc/8.4.1

**Comment by Algiane** [comment]
Only the `pygeosx.so` shared library is installed in the `$CMAKE_INSTALL_PREFIX/lib` directory so the other shared libraries against which is built pygeosx are not found.
It can be solved:
  - by adding the path toward the other libs to the `LD_LIBRARY_PATH` variable (so the build directory). It is not clean and not usual as it means that the build directory cannot be deleted without breaking the runtime;
   - by installing all the shared libs in the same location (usual way)

**Comment by rrsettgast** [comment]
The install command was accidentally removed. I will create a quick patch.

**Comment by acitrain** [comment]
Thanks Randy!

I'll close my PR linked with this issue when the patch will be operational
