### ISSUE TITLE
Understanding Boundary Conditions for Compositional Multi-Phase Well Solvers

### ISSUE THREAD

**Issue by CharlesHostetler** [GEOS-DEV/GEOS#3325]
I am doing a carbon sequestration problem.  I am modeling the reservoir only.  When I worked with models with internally generated meshes, it seemed to me that the vertical faces of the model domain and the top and bottom were no-flow boundaries.  I could set up hydrostatic initial conditions in the reservoir and watch the pressure change across the model as a function of time as CO2 was injected through a well.  

Now I am trying to run a model with an external mesh that was generated by GMSH.  In my first run it looks like all of the vertical faces of the model domain are open, not no-flow; and I can't tell for sure if the top and bottom are open or no-flow.  

Is there a quick any easy way to specify no-flow boundary conditions to the faces, top, and bottom of an externally-generated grid?  I do not want to use Dirichlet conditions along the sides, which is what all the examples and tutorials seem to suggest.  

Thanks!

**Comment by paveltomin** [comment]
no-flow boundary conditions is the default behavior, no need to specify anything
