### ISSUE TITLE
Permeability Tensor Orientation in Global or. Local Coordinate Systems?

### ISSUE THREAD

**Issue by FishYNY** [GEOS-DEV/GEOS#3351]
Hi, there. 

Is the permeability tensor in the input example defined in the local coordinate system (dependent on the grid partition) or in the global coordinate system? For instance, in the provided example:

```xml
<ConstantPermeability
  name="rockPermfault"
  permeabilityComponents="{ 1e-15, 1e-15, 1.0e-15 }"/>
```

Are the specified permeabilities in the x, y, and z directions aligned with the directions defined in the global coordinate system?

**Comment by CusiniM** [comment]
If I understand your question correctly, the permeability tensor is defined in the global coordinate system but we should clarify what you mean by "global".
