### ISSUE TITLE
Strain components' naming issue

### ISSUE THREAD

**Issue by sytuannguyen** [GEOS-DEV/GEOS#3368]
**Describe the issue**
The strain component xz is actually named with the index "yz" and vice versa.

**Proposed cleanup**
Correct the names of the strain components: "yz" to "xz" and "xz" to "yz"

**Additional context**

**Comment by jhuang2601** [comment]
@ryar9534 Can you help to take a look on this issue?

**Comment by ryar9534** [comment]
Apparently the vtk ordering of voight notation and what is done in the GEOS internal are different, I will fix this shortly

**Comment by rrsettgast** [comment]
This is confusing. There is only one voight ordering...isnt there?

**Comment by ryar9534** [comment]
@sytuannguyen can you try the change in #3373 and see if that fixes things?
