### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by tao28005** [GEOS-DEV/GEOS#3404]
Hello,

Compilation in release mode stopped with the following error messages:

codes/GEOS/src/coreComponents/physicsSolvers/contact/SolidMechanicsALMKernelsBase.hpp:295:26: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  295 |       localIndex const & f1 = elemsToFaces[k][1];
          |                                          ^~

codes/GEOS/src/coreComponents/physicsSolvers/contact/SolidMechanicsALMKernelsBase.hpp:295:26: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
  295 |       localIndex const & f1 = elemsToFaces[k][1];
      |                                              ^~

Thanks

**Comment by paveltomin** [comment]
fixed
