### ISSUE TITLE
Unable to do make install after compiling GEOS - schema files error

### ISSUE THREAD

**Issue by sohanjit123** [GEOS-DEV/GEOS#3462]
When i try to do make install after compiling geos. At 67% I get the error

ValueError: Obsolete autogenerated .rst table files detected:SpatialPartition_other.rst
  CompositeFunction.rst
  SymbolicFunction.rst
  BoundedPlane_other.rst
  LagrangianContact_other.rst
  LagrangianContact.rst
  PermeabilityBase.rst
  CompositeFunction_other.rst
  SymbolicFunction_other.rst
  BoundedPlane.rst
  PermeabilityBase_other.rst

**Comment by paveltomin** [comment]
remove those files and try again
