### ISSUE TITLE
Set the default value of "isFaceSeparable" to be 1 if it is not explicitly set in the input file

### ISSUE THREAD

**Issue by WuHuiLLNL** [GEOS-DEV/GEOS#614]
Issue description: In surface generator, a field named "isFaceSeparable' is used to tell the solver which face can be separated during fracturing. The default value of this field is 0, meaning that all the faces are not separable. Currently, we need to manually define a set and specify the "isFaceSeparable" field to be 1 for the set. If such a set is not defined, then the fracture will not propagate.

Solution: Before fracturing happens, check the "isFaceSeparable" field. If this field is 0 for all the faces, then change the field to be 1 for all the faces.

**Comment by TotoGaz** [comment]
We're currently revisiting our way to import fractures.
Thus we won't change the current behavior, but bring other solutions upstream.
