### ISSUE TITLE
Avoid use of dimensional tolerances

### ISSUE THREAD

**Issue by andrea-franceschini** [GEOS-DEV/GEOS#896]
**Description**
As now, `LagrangianContactMechanics` (#799) uses some dimensional tolerances for displacement jumps and tractions.
We should get rid of them, using some internal scaling, based on stiffness, characteristic length or similar ...

**Comment by rrsettgast** [comment]
@andrea-franceschini @CusiniM Is this done?

**Comment by andrea-franceschini** [comment]
Based on the same idea behind the stabilization, a fairly robust method for calculating dimensionless tolerances has been proposed, see [computeTolerances](https://github.com/GEOSX/GEOSX/blob/14e30d15aebaae649f40277d5979fa77646dd782/src/coreComponents/physicsSolvers/contact/LagrangianContactSolver.cpp#L270-L416), however manual corrections are still required for some cases.

If @CusiniM and you agree, I would propose to close this issue now and, if needed, create a new one once we find a case where a revision of the tolerance calculation is required.

**Comment by TotoGaz** [comment]
Let's follow your advice @andrea-franceschini !
